#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This installs MyPaint via Flatpak and repo in a way that is more sure to work on 64 bit systems.
## When finished, you can run it as a Flatpak app (via vmypaint) and as a normal app.

# How to use:
## sudo ./install-mypaint64


## Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo bash install-mypaint64
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-mypaint64
"
exit 22; fi

# Check status
. /var/local/vrk/machineinfo
if [ "${MYPAINT_INSTALLED}" = "YES" ]; then
echo "MyPaint already installed."
exit 0; fi


# Install
## Verify Flatpak
apt install -y flatpak
## MyPaint via Flatpak
flatpak install -y --from https://raw.githubusercontent.com/mypaint/mypaint/master/flatpak/mypaint-stable.flatpakref
## MyPaint via APT
apt install -y mypaint mypaint-data-extras

# Config
echo "MYPAINT_INSTALLED=\"YES\"" >> /var/local/vrk/machineinfo 
touch /var/local/vrk/.mypaintinstalled

# Finish
apt autoremove -y
echo "MyPaint should now be installed to the newest version.
But, it won't show up until you log in again.
If you want to be strange, run MyPaint via Flatpak from the terminal with this: vmypaint
"

