#!/bin/sh
#inkVerbBoss! verb.ink

# This installs Vubuntu Desktop and Vubuntu Studio Lite
## This runs: install-vubuntu-studiolite, install-vubuntu-desktop, and install-vubuntu-vallpaper
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo ./install-vubuntu


# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-vubuntu
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-vubuntu
"
exit 22
fi

# Installed?
## Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22
fi
## Check if installed for this user
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Vrk is installed on this machine, but has yet to be installed for this user. See README.md"
exit 22
fi

# Verify the interactives first
apt install -y msttcorefonts jackd2

# Add the graphix PPA
/var/local/vrk/boss/install-grfx

# Vubuntu Desktop
/var/local/vrk/boss/install-vubuntu-desktop

# Vubuntu StudioLite
/var/local/vrk/boss/install-vubuntu-studiolite

