#!/bin/sh
#inkVerbSurfer! verb.ink

# This installs a few syntax themes for gedit

# How to use:
## sudo install-geditthemes


# Set user
VRK_USER=${SUDO_USER}

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo updatevrk
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo updatevrk
"
exit 22
fi

# Git pull
cd /opt/vrk
mkdir .gedit-themes.tmp
cd .gedit-themes.tmp
git clone https://github.com/Peter-van-der-Velde/Two-Dark.git
git clone https://github.com/dracula/gedit.git

# Copy the themes
mv Two-Dark/theme_two_dark.xml /usr/share/gtksourceview-3.0/styles/
mv gedit/dracula.xml /usr/share/gtksourceview-3.0/styles/
cd ..
rm -r .gedit-themes.tmp

# Finish
echo "Git themes added and installed."
