#!/bin/sh
#inkVerbBoss! verb.ink

# This installs the Inkscape extension Export PDF CMYK

# How to use:
## sudo install-pdfcmyk


# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-pdfcmyk
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-pdfcmyk
"
exit 22; fi

# Install
cp /opt/vrk/donjon/inkscape/ExportPDTCMYK/export-pdf-cmyk.inx /usr/share/inkscape/extensions/
cp /opt/vrk/donjon/inkscape/ExportPDTCMYK/export-pdf-cmyk.py /usr/share/inkscape/extensions/

# Finish
echo "Export PDF CMYK Inkscape extension installed.
"

