#!/bin/sh
#inkVerbBoss! verb.ink

# This installs and/or updates Vubuntu native wallpapers
## This is automatically run by: install-vubuntu-desktop and install-vubuntu
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo ./install-vubuntu-vallpaper


# Set Room name
VALL_ROOM="vubuntu"

# Set user
VRK_USER=${SUDO_USER}

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-vubuntu-vallpaper
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-vubuntu-vallpaper
"
exit 22
fi

# Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22
fi

# Install/Update Vallpaper
## The actuall Valls exist here under lock and key.
mkdir -p /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM}
## The images are duplicated here for hard system link use.
mkdir -p /usr/share/images/vall

# Install/Reset the Vubuntu Vallpaper Room
## The /usr/share/images folder is used by Xfce and by set-vall and Vallpaper rooms and chrons
rm -rf /var/local/vall/rooms/${VALL_ROOM}
cp -r /var/local/vrk/donjon/vallpaper/${VALL_ROOM} /var/local/vall/rooms/
rm -rf /usr/share/images/vall/${VALL_ROOM}
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM} /usr/share/images/vall/

# Add Avatar icons (but not Xfce)
if [ -d "/usr/share/pixmaps/faces/" ]; then
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/avitar-icons/* /usr/share/pixmaps/faces/
fi

# Install Vubuntu vallpapers
## Global (GNOME, KDE, Budgie)
### If "backgrounds" doesn't exist (KDE, cough cough)
if [ ! -d /usr/share/backgrounds ]; then
mkdir -p /usr/share/backgrounds
fi
if [ ! -d /usr/share/gnome-background-properties ]; then
mkdir -p /usr/share/gnome-background-properties
fi
rm -rf /usr/share/backgrounds/${VALL_ROOM}
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM} /usr/share/backgrounds/
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/${VALL_ROOM}-wallpapers.xml /usr/share/gnome-background-properties/
## Xfce
if || [ "${DESKTOP_SESSION}" = "xubuntu" ] || [ "${DESKTOP_SESSION}" = "xfce" ] ; then
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/*.png /usr/share/xfce4/backdrops/
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/*.jpg /usr/share/xfce4/backdrops/
fi
## UbuntuStudio
if [ "${DESKTOP_SESSION}" = "ubuntustudio" ]; then
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/*.png /usr/share/backgrounds/ubuntustudio/
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/*.jpg /usr/share/backgrounds/ubuntustudio/
fi
### If Ubuntu Studio is already installed after Xfce, add those
ln -sfn /usr/share/backgrounds/ubuntustudio/* /usr/share/xfce4/backdrops/
### If not, remove any broken symlinks
cd /usr/share/xfce4/backdrops/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done
fi
## MATE
if [ -d /usr/share/mate-background-properties ]; then
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/${VALL_ROOM}-wallpapers.xml /usr/share/mate-background-properties/
fi
## Cinnamon
if [ -d /usr/share/cinnamon-background-properties ]; then
ln -sfn /var/local/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/linuxmint-${VALL_ROOM}.xml /usr/share/cinnamon-background-properties/
fi

# Global lock screen GNOME (run in this sudo, it sets for root, thus all)
gsettings set org.gnome.desktop.screensaver picture-uri file:///usr/share/images/vall/vubuntu/inkVerb-Carbon.png
## More here:
# http://fabhax.com/technology/change-wallpapers-in-gnome-3.4/
## Unity? lagacy
#gsettings set com.canonical.unity-greeter background '/usr/share/images/vall/vubuntu/inkVerb-Carbon.png'

# Finish
echo "
Vubuntu native wallpapers are installed and up to date.
"

