#!/bin/sh
#inkVerbBoss! verb.ink

# This installs developer tools for Ubuntu
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo install-vubuntu-developer


# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vubuntu-developer
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vubuntu-developer
"
exit 22; fi

# Check if Vubuntu Developer installed
if [ "${VUBUNTU_DEVELOPER_INSTALLED}" = "YES" ]; then
echo "Vubuntu Developer apps already installed."
exit 0; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vubuntu-apps
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vubuntu-apps
"
exit 22; fi


# Include the configs
. /home/${SUDO_USER}/.vrk/configs/lang/stationuser-dirs_CURRENT
. /opt/vrk/machineinfo

# Check CPU version
PROCVNO=$(dpkg --print-architecture)

# Install the packages
echo "
Installing Vubuntu Developer

First, updates and fonts...
"

# Add repos
/opt/vrk/boss/install-repos

# Update & Upgrade
apt update -y --fix-missing
apt upgrade -y --fix-missing
apt update -y --fix-missing
apt install -yf

## Verify interactives first, and then the fonts
#apt install -y ttf-mscorefonts-installer # Fails download
chkfile=/opt/vrk/.inst-dev-1
if [ ! -f "$chkfile" ]; then
apt install -y jackd2 fonts-cantarell lmodern ttf-aenigma ttf-georgewilliams ttf-bitstream-vera ttf-sjfonts tv-fonts tex-gyre
echo "
Fonts are now installed. Now doing some basic tools...
"
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-2
if [ ! -f "$chkfile" ]; then
apt install -y zip p7zip-full gzip tilda docky kate retext gedit nautilus grabc gparted shutter kazam obs-studio
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-3
if [ ! -f "$chkfile" ]; then
echo "Vrk would normally install Atom here, but that doesn't seem to work out. Moving on..."
#apt install -y atom
#wait
## Redundant from install-vubuntu-desktop
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-4
if [ ! -f "$chkfile" ]; then
apt install -y chromium-browser thunderbird firefox
touch $chkfile; fi
echo "
Tools done. Now doing browsers...
"
#apt install -y midori #DEV Delayed until 18.04 is out of beta
if [ "${PROCVNO}" = "amd64" ]; then
 if [ ! -f "/opt/vrk/.vubuntu-chrome" ]; then
chkfile=/opt/vrk/.inst-dev-5
if [ ! -f "$chkfile" ]; then
echo "You are running a 64 bit processor, so you get Google Chrome! XD..."
  vrk_add_repo_chrome="deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
  if ! grep -q "^deb .*$vrk_add_repo_chrome" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
rm -f linux_signing_key.pub
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
rm -f linux_signing_key.pub
touch /opt/vrk/.vubuntu-chrome
  fi
apt update -y --fix-missing
apt install -y google-chrome-stable
touch $chkfile; fi
 fi
fi
echo "
Office stuff done. Doing web dev favorites...
"
chkfile=/opt/vrk/.inst-dev-6
if [ ! -f "$chkfile" ]; then
apt install -y git vim filezilla meld ssh curl wget
echo "
Web dev happy. Getting graphic design, Inkscape, Blender, GIMP, Darktable, MyPaint, ICC printing profiles...
"
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-7
if [ ! -f "$chkfile" ]; then
apt install -y inkscape blender gimp gimp-plugin-registry darktable krita icc-profiles
apt install -y pencil2d mypaint mypaint-data-extras

### Inkscape Export PDF CMYK extension
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-8
if [ ! -f "$chkfile" ]; then
/opt/vrk/boss/install-pdfcmyk

echo "
Graphic design done. VLC, Shotcut...
"
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-9
if [ ! -f "$chkfile" ]; then
apt install -y vlc vlc-data browser-plugin-vlc
#apt install -y mplayer2 #broken in Ubuntu 18.04
echo "
Media done. Audiophile tools...
"
## pulseaudio & pavucontrol for mixing & monitor control in Audacity
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-10
if [ ! -f "$chkfile" ]; then
apt install -y audacity kid3
#apt install -y yate-qt4 #broken in Ubuntu 18.04
## Audacity DeClicker & DeEsser http://forum.audacityteam.org/viewtopic.php?f=42&t=79278&p=245549
cd /usr/share/audacity/plug-ins/
wget -O DeClicker.ny http://forum.audacityteam.org/download/file.php?id=10124
wget -O DeEsser.ny http://forum.audacityteam.org/download/file.php?id=10125
echo "Sound's great. (hehe) Getting desktop goodies...
"
#apt install -y ubuntu-restricted-extras # removing the mscorefonts installer & testing if this really necessary? Moved to: install-ubuntustudio
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-11
if [ ! -f "$chkfile" ]; then
apt install -y alsa-oss libasound2 libasound2-plugins
touch $chkfile; fi
chkfile=/opt/vrk/.inst-dev-12
if [ ! -f "$chkfile" ]; then
apt install -y gnome-music gnome-photos planner gromit gnome-chess
touch $chkfile; fi
#apt install -y dia-gnome #broken in Ubuntu 18.04

# Remove every $chkfile
rm /opt/vrk/.inst-dev-*

# Set config
echo "VUBUNTU_DEVELOPER_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo
touch /home/${SUDO_USER}/.vrk/configs/.Developer
## Remove repo temp progress files
rm -f /opt/vrk/.vubuntu-developer-*

# Cleanup
apt autoremove -y

# Finish
echo "
Vubuntu Developer is all set.
"
