#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This installs PydioSync

# DEV VERSION!! PydioSync currently doesn't work on Linux, at least not this way. Contribute or stay tuned.
echo "Actually, this is only in development because Pydio isn't ready for Linux yet. Feel free to help out with git pull requests."
exit 0

# How to use:
## sudo ./install-pydio


# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-pydio
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-pydio
"
exit 22
fi

# Check status
. /var/local/vrk/machineinfo
if [ "${PYDIO_INSTALLED}" = "YES" ]; then
echo "Pydio already installed."
exit 0; fi

# Install
## Dependencies
apt install python-pip
pip install --upgrade pip
pip install git+https://github.com/pydio/pydio-sync.git
#DEV: This is not finished and Pydio doesn't always work as of yet.

# Config
echo "PYDIO_INSTALLED=\"YES\"" >> /var/local/vrk/machineinfo
touch /var/local/vrk/.pydioinstalled

# Finish
apt autoremove -y
echo "PydioSync should now be installed to the newest version.
"

