#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This installs Dropbox

# How to use:
## sudo bash install-dropbox


# Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo bash install-dropbox
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-dropbox
"
exit 22; fi

# Check status
. /var/local/vrk/machineinfo
if [ "${DROPBOX_INSTALLED}" = "YES" ]; then
echo "Dropbox already installed."
exit 0; fi


# Install
apt install -yf nautilus-dropbox

# Config
echo "DROPBOX_INSTALLED=\"YES\"" >> /var/local/vrk/machineinfo
touch /var/local/vrk/.dropboxinstalled

# Finish
apt autoremove -y
echo "Dropbox should now be installed to the newest version and will begin its download shortly...
"

