#!/bin/sh
#inkVerbBoss! verb.ink

# This installs Vubuntu Desktop and Vubuntu Studio Lite
## This runs: install-grfx, install-vubuntu-studiolite, and install-vubuntu-desktop
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo install-vubuntu


# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vubuntu
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vubuntu
"
exit 22; fi

# Include the config
. /opt/vrk/machineinfo

# Update & Upgrade
apt update -y --fix-missing
apt upgrade -y --fix-missing
apt install -yf
apt update -y --fix-missing

# Verify the interactives first
apt install -y jackd2
apt install -y ttf-mscorefonts-installer

# Add the graphix PPA
/opt/vrk/boss/install-grfx

# Vubuntu Desktop
/opt/vrk/boss/install-vubuntu-desktop

# Vubuntu StudioLite
/opt/vrk/boss/install-vubuntu-studiolite
