#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This installs libsass and sassc
##DEV: Right now sassc just doesn't seem to want to install in the known universe.

# How to use:
## sudo ./install-adapta


# Set user
VRK_USER=${SUDO_USER}

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./updatevrk
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./updatevrk
"
exit 22
fi

# Check status
. /var/local/vrk/machineinfo
if [ "${ADAPTA_INSTALLED}" = "YES" ]; then
echo "Extra repos already installed."
exit 0; fi

# Add repo
if [ ! -f "/var/local/vrk/.adaptarepoinstalled" ]; then
add-apt-repository -y ppa:tista/adapta
apt update
touch /var/local/vrk/.adaptarepoinstalled
fi

# Install Adapta
apt install -y adapta-gtk-theme

# Config
echo "ADAPTA_INSTALLED=\"YES\"" >> /var/local/vrk/machineinfo

# Finish
echo "Adapta added and installed."

