#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This installs Vubuntu Desktop settings, theming, and Vubuntu Wallpaper
## This is automatically run by: install-vubuntu
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo ./install-vubuntu-desktop


# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-vubuntu-desktop
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-vubuntu-desktop
"
exit 22; fi

# Check if Vubuntu Desktop installed
if [ "${VUBUNTU_DESKTOP_INSTALLED}" = "YES" ]; then
echo "Vubuntu desktop apps already installed."
exit 0; fi

# Check if Vubuntu Desktop installed (again)
if [ -f /var/local/vrk/.vubuntu-desktop-installed ]; then
echo "Vubuntu Desktop already installed on this machine."
exit 0; fi

# Include the config
. /var/local/vrk/machineinfo

# Update & Upgrade
apt update -yf --fix-missing
apt upgrade -yf --fix-missing
apt install -yf

# Ubuntu Studio Wallpapers, GTK configs, GNOME/Unity Tweak Tools, Xfce Dashboard, Guake, Docky, Variety
apt install -y conky conky-all ubuntustudio-wallpapers guake docky gnome-terminal variety htop gtk-theme-config

# LibreOffice (done now for vubuntu-desktop settings dependencies)
apt install -y libreoffice libreoffice-writer libreoffice-calc libreoffice-impress libreoffice-draw libreoffice-base libreoffice-math libreoffice-gnome libreoffice-kde

# Git, bc, build tools, and theme dependencies (may be redundant, but never can be too sure, here they all are from each theme's dependency instructions)
apt install -y git bc wmctrl dconf-cli autoconf automake libtool intltool inkscape cmake krita gimp
apt install -y gnome-themes-standard libgdk-pixbuf2.0-dev libglib2.0-dev libgtk-3-dev libxml2-utils gtk3-engines-unico gtk2-engines-murrine gtk2-engines-pixbuf pkg-config python3 ruby-bundler ruby-sass
## Specific for making Adapta themes (may only be used to make Adapta, but why not)
apt install -y sassc libsass0 librsvg2-dev 

# Non-Budgie theme dependencies
#DEV: Budgie doesn't need these becuase it has it's native theme and may lack repos
## Some of these Adapta-make packages have alternate names, just in case, but this will probably get rejected, do not use in Budgie
if [ "$LINUX_DISTRO" = "ubuntu" ] || [ "$LINUX_DISTRO" = "gnome" ]; then
apt install -y gdk-pixbuf2-devel glib2-devel librsvg2-devel libsass libxml2 pkgconfig cutomake; fi

# Icon theme for LibreOffice
apt install -y libreoffice-style-sifr libreoffice-style-galaxy libreoffice-style-hicontrast libreoffice-style-human libreoffice-style-oxygen libreoffice-style-tango
## Add the Images Office 2013 theme
ln -sfn /var/local/vrk/donjon/libreoffice/images_voffice.zip /usr/lib/libreoffice/share/config/
ln -sfn /var/local/vrk/donjon/libreoffice/images_voffice.zip /usr/share/libreoffice/share/config/

# Wallpapers
/var/local/vrk/boss/install-vubuntu-vallpaper

# Themes
/var/local/vrk/boss/themicons-git-upstall

# Gedit always opens a new window, not tab-clustering (possible solutions)
#notyet

# Window Snapping
#notyet

# Global
# Global #

# Unity
if [ "${LINUX_DISTRO}" = "ubuntu" ]; then
/var/local/vrk/donjon/vubuntu-unity-notifications-off
apt install -y unity-tweak-tool 
fi
# Unity #


# GNOME
if [ "${LINUX_DISTRO}" = "gnome" ]; then
apt install -y gnome-tweak-tool
fi
# GNOME #



# Xubuntu/UbuntuStudio
if [ "${LINUX_DISTRO}" = "xubuntu" ] || [ "${LINUX_DISTRO}" = "ubuntustudio" ] ; then
## xfDashboard
#NO LONGER IN TESTING, normal repos may work, just in case
add-apt-repository -y ppa:xubuntu-dev/extras
apt update
apt install -y xfdashboard

fi
# Xubuntu #


# KDE
#if [ "$LINUX_DISTRO" = "/usr/share/xsessions/plasma" ]; then

#fi
# KDE #


# MATE
#if [ "$LINUX_DISTRO" = "mate" ]; then

#fi
# MATE #


# Cinnamon
#if [ "$LINUX_DISTRO" = "cinnamon" ]; then

#fi
# Cinnamon #


# Mint_XFCE
#if  [ "${LINUX_DISTRO}" = "xfce" ]; then

#fi
# Mint_Xfce

# Set configs
echo "VUBUNTU_DESKTOP_INSTALLED=\"YES\"" >> /var/local/vrk/machineinfo
touch /var/local/vrk/.vubuntu-desktop-installed

# Touch LibreOffice configs
echo "
Launching LibreOffice quick, if it doesn't cloes automatically, just close it yourself...
"
## Add the ampersand to the end of the line so that the desktop app doesn't lock the terminal
libreoffice &
## Wait for the LibreOffice script to finish
sleep 1
## Kill the name of the "splash screen" process that eventually ends up running
killall oosplash

# Cleanup
apt autoremove -y

# Finish
echo "Vubuntu Desktop is now installed. Now you can run set-vrk-desktop"
sleep 2

