#!/bin/sh
#inkVerbBoss! verb.ink

# This autoinstalls drivers for devices as listed with `sudo ubuntu-drivers devices`

# How to use:
## sudo install-drivers


# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-drivers
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-drivers
"
exit 22; fi

# Check status
. /opt/vrk/machineinfo
if [ "${VRK_DRIVERS_INSTALLED}" = "YES" ]; then
echo "Devices autoinstall drivers already installed."
exit 0; fi


# Install
# Get a list of driver candidate devices with this: sudo ubuntu-drivers devices
ubuntu-drivers autoinstall

# Config
echo "VRK_DRIVERS_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo
touch /opt/vrk/.driversinstalled

# Finish
apt autoremove -y
echo "Drivers autoinstall completed. Manage in:

Software & Updates > System Settings > Additional Drivers
"
