#!/bin/sh
#inkVerbBoss! verb.ink

# This adds some useful repos

# How to use:
## sudo install-repos


# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-grfx
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-repos
"
exit 22
fi

# Check status
. /opt/vrk/machineinfo
if [ "${REPOS_INSTALLED}" = "YES" ]; then
echo "Extra repos already installed."
exit 0; fi

# Add via apt
## More Canonical repos
add-apt-repository -y universe
add-apt-repository -y main
add-apt-repository -y restricted
add-apt-repository -y multiverse
## OBS faster channel
#add-apt-repository -y ppa:obsproject/obs-studio #broken?
##dpkg: error processing archive /var/cache/apt/archives/obs-studio_22.0.2-0obsproject1~bionic_amd64.deb (--unpack):
## trying to overwrite '/usr/share/obs/libobs/bicubic_scale.effect', which is also in package libobs0:amd64 21.0.2+dfsg1-1

### DEV: Atom install script always fails
### Atom
#cd /home/${SUDO_USER}/.vrk
#mkdir -p .atom-key.tmp
#cd .atom-key.tmp
#wget https://packagecloud.io/AtomEditor/atom/gpgkey | apt-key add -; wait
#sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/#sources.list.d/atom.list'; wait
#cd ..
#rm -r .atom-key.tmp

## Blender faster channel
add-apt-repository -y ppa:thomas-schiex/blender
## Kdenlive faster channel
add-apt-repository -y ppa:kdenlive/kdenlive-stable
## Shotcut
add-apt-repository -y ppa:haraldhv/shotcut
## LibreOffice
add-apt-repository -y ppa:libreoffice/ppa
## KDE for the current version of Kate
add-apt-repository -y ppa:kubuntu-ppa/backports
## Update
apt update -y --fix-missing

## Add manually
#if [ ! -f "/opt/vrk/.vubuntu-studiolite-repo" ]; then
### Check at each stage to prevent duplication
#### canonical partner
 if [ ! -f "/opt/vrk/.vubuntu-repo-partner"-$(lsb_release -sc) ]; then
vrk_ppa_repo_partner="deb http://archive.canonical.com/ $(lsb_release -sc) partner"
 if ! grep -q "^deb .*$vrk_ppa_repo_partner" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
add-apt-repository -y "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
touch /opt/vrk/.vubuntu-repo-partner-$(lsb_release -sc)
  fi
 fi
##### main universe restricted multiverse
# if [ ! -f "/opt/vrk/.vubuntu-repo-multiverse"-$(lsb_release -sc) ]; then
# vrk_add_repo_multiverse="deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
#  if ! grep -q "^deb .*$vrk_add_repo_multiverse" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
#add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
#touch /opt/vrk/.vubuntu-repo-multiverse-$(lsb_release -sc)
#  fi
# fi

# Config
echo "REPOS_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo
touch /opt/vrk/.reposinstalled

# Finish
apt update -y --fix-missing

echo "Repos added."

