#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This installs MyPaint

# How to use:
## sudo ./install-mypaint64


# Actually, this is in DEV and won't be necessary when myPaint gets working on x64 bit machines.
## If you want to help below, in the "Install" area to do this properly, make a git pull request for this file.
echo "This doesn't work, it's only in dev."

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo bash install-nextcloud
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-nextcloud
"
exit 22
fi

# Check status
if [ -f /home/${SUDO_USER}/.vrk/configs/mypaintstatus ]; then
. /home/${SUDO_USER}/.vrk/configs/mypaintstatus
if [ "${MYPAINTSTATUS}" = "INSTALLED" ]; then
echo "MyPaint already installed. Nothing to do."
exit 0; fi
fi

# Install
## Verify Flatpak
sudo apt install flatpak -y
## MyPaint
flatpak install -y --from https://raw.githubusercontent.com/mypaint/mypaint/master/flatpak/mypaint-stable.flatpakref

# Config
echo "#!/bin/sh
# Nextcloud repo status

MYPAINTSTATUS="INSTALLED"
" > /home/${SUDO_USER}/.vrk/configs/mypaintstatus

# Finish
apt autoremove -y
echo "MyPaint should now be installed to the newest version.
But, it won't show up until you log in again.
Run MyPaint from the terminal with this: vmypaint
"

