#!/bin/sh
#inkVerbBoss! verb.ink

# This installs Aptana Studio
##DEV: This is only in dev and should be expanded on later
##ref: http://linuxpitstop.com/install-aptana-studio-3-on-centos-and-ubuntu/

# How to use:
## sudo install-aptanastudio


# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-flash
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-flash
"
exit 22; fi


# Install
echo "Here are the instructions:
http://linuxpitstop.com/install-aptana-studio-3-on-centos-and-ubuntu/
"

# Finish
apt autoremove -y
echo "Flash installed.
"

