#!/bin/sh
#inkVerbBoss! verb.ink

# This installs Vubuntu Desktop and Vubuntu Minimum
## This runs: install-grfx, install-vubuntu-minimum, and install-vubuntu-desktop
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo ./install-vubuntu-min


# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-vubuntu-min
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-vubuntu-min
"
exit 22; fi

# Include the config
. /var/local/vrk/machineinfo

# Update & Upgrade
apt update -y --fix-missing
apt upgrade -y --fix-missing
apt install -yf
apt update -y --fix-missing

# Verify the interactives first
apt install -y jackd2

# Add the graphix PPA
/var/local/vrk/boss/install-grfx

# Vubuntu Minimum
/var/local/vrk/boss/install-vubuntu-minimum

# Vubuntu Desktop
/var/local/vrk/boss/install-vubuntu-desktop

