#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This adds some useful repos

# How to use:
## sudo ./install-repos


# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-grfx
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-grfx
"
exit 22
fi

# Check status
. /var/local/vrk/machineinfo
if [ "${REPOS_INSTALLED}" = "YES" ]; then
echo "Extra repos already installed."
exit 0; fi

## Add some extra repositories
if [ ! -f "/var/local/vrk/.vubuntu-studiolite-repo" ]; then
### Check at each stage to prevent duplication
#### canonical partner
 if [ ! -f "/var/local/vrk/.vubuntu-studiolite-repo-partner" ]; then
 vrk_ppa_repo_partner="deb http://archive.canonical.com/ $(lsb_release -sc) partner"
  if ! grep -q "^deb .*$vrk_ppa_repo_partner" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
add-apt-repository -y "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
touch /var/local/vrk/.vubuntu-studiolite-repo-partner-$(lsb_release -sc)
  fi
 fi
#### main universe restricted multiverse
 if [ ! -f "/var/local/vrk/.vubuntu-studiolite-repo-multiverse" ]; then
 vrk_add_repo_multiverse="deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
  if ! grep -q "^deb .*$vrk_add_repo_multiverse" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
touch /var/local/vrk/.vubuntu-studiolite-repo-multiverse-$(lsb_release -sc)
  fi
 fi

# Config
echo "REPOS_INSTALLED=\"YES\"" >> /var/local/vrk/machineinfo
touch /var/local/vrk/.reposinstalled

# Finish
apt update
echo "Repos added."

