#!/bin/sh
#inkVerbBoss! verb.ink

# This installs Nextcloud

# How to use:
## sudo bash install-nextcloud


# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo bash install-nextcloud
"
exit 22;  fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-nextcloud
"
exit 22; fi

# Check status
. /opt/vrk/machineinfo
if [ "${NC_INSTALLED}" = "YES" ]; then
echo "Nextcloud already installed."
exit 0; fi


# Install
if [ ! -f "/opt/vrk/.vubuntu-nextcloud" ]; then
add-apt-repository ppa:nextcloud-devs/client -y
touch /opt/vrk/.vubuntu-nextcloud
fi
apt update -y --fix-missing
apt install nextcloud-client -y

# Config
echo "NC_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo
touch /opt/vrk/.nextcloudinstalled

# Finish
apt autoremove -y
rm /opt/vrk/.vubuntu-nextcloud
echo "Nextcloud should now be installed to the newest version.
"

