#!/bin/sh
#inkVerbBoss! verb.ink

# This installs a "lite" version of Ubuntu Studio
## This is automatically run by: install-vubuntu
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo ./install-vubuntu-apps


# Set user
VRK_USER=${SUDO_USER}

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-vubuntu-studiolite
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-vubuntu-studiolite
"
exit 22
fi

# Check if Vubuntu StudioLite installed
. /var/local/vrk/machineinfo
if [ "${VUBUNTU_STUDIOLITE_INSTALLED}" = "YES" ]; then
echo "Vubuntu StudioLite already installed."
exit 0
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-vubuntu-apps
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-vubuntu-apps
"
exit 22
fi

# Include the configs
. /home/${SUDO_USER}/.vrk/configs/lang/stationuser-dirs_CURRENT
. /var/local/vrk/machineinfo

# Check CPU version
PROCVNO=$(dpkg --print-architecture)

# Install the packages
echo "
Installing Vubuntu Studio Lite

First, updates and fonts. Get ready to agree to EULA...
"

### Done
touch /var/local/vrk/.vubuntu-studiolite-repo
fi

## Update & Upgrade
apt update && apt upgrade -yf --fix-missing

## Verify interactives first, and the rest of the fonts
apt install -y ttf-mscorefonts-installer jackd2
apt install -y fonts-cantarell lmodern ttf-aenigma ttf-georgewilliams ttf-bitstream-vera ttf-sjfonts tv-fonts
echo "
Fonts are now installed. Now doing some basic tools...
"
apt install -y zip p7zip-full gzip guake phatch docky gedit kate nautilus grabc gparted shutter kazam
# Redundant from install-vubuntu-desktop
apt install -y libreoffice libreoffice-writer libreoffice-calc libreoffice-impress libreoffice-draw libreoffice-base libreoffice-math libreoffice-gnome libreoffice-kde
echo "
Tools done. Now doing browsers...
"
apt install -y midori thunderbird firefox
apt install -y chromium-browser djview-plugin
if [ "${DESKTOP_SESSION}" = "ubuntu" ]; then
apt install -y unity-chromium-extension
fi
if [ "${DESKTOP_SESSION}" = "gnome" ]; then
apt install -y epiphany-browser gconf-editor
fi
if [ "${PROCVNO}" = "amd64" ]; then
 if [ ! -f "/var/local/vrk/.vubuntu-studiolite-chrome" ]; then
echo "You are running a 64 bit processor, so you get Google Chrome! XD..."
  vrk_add_repo_chrome="deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
  if ! grep -q "^deb .*$vrk_add_repo_chrome" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
rm -f linux_signing_key.pub
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
rm -f linux_signing_key.pub
touch /var/local/vrk/.vubuntu-studiolite-chrome
  fi
apt update 
apt install -y google-chrome-stable
 fi
fi
echo "
Tools done. Now doing Google Earth...
"
if [ "${PROCVNO}" = "amd64" ]; then
 if [ ! -f "/var/local/vrk/.vubuntu-studiolite-earth64" ]; then
rm -f google-earth-stable_current_amd64.deb*
wget https://dl.google.com/dl/earth/client/current/google-earth-stable_current_amd64.deb
dpkg -i google-earth-stable*.deb
apt install -yf
rm -f google-earth-stable_current_amd64.deb*
touch /var/local/vrk/.vubuntu-studiolite-earth64
 fi
fi
if [ "${PROCVNO}" = "i386" ]; then
 if [ ! -f "/var/local/vrk/.vubuntu-studiolite-earth386" ]; then
rm -f google-earth-stable_current_i386.deb*
wget https://dl.google.com/dl/earth/client/current/google-earth-stable_current_i386.deb
dpkg -i google-earth-stable*.deb
apt install -yf
rm -f google-earth-stable_current_i386.deb*
touch /var/local/vrk/.vubuntu-studiolite-earth386
 fi
fi
echo "
Google Earth done. Flash and some more office stuff...
"
apt install -y adobe-flashplugin libreoffice scribus
echo "
Flash and office stuff done. Doing web dev favorites...
"
apt install -y git vim guake-indicator filezilla meld
echo "
Web dev happy. Getting graphic design, Inkscape, Blender, GIMP, Darktable, MyPaint...
"
## The beta GIMP 2.9
#add-apt-repository -y ppa:otto-kesselgulasch/gimp-edge
#apt update && sudo apt install -y gimp gimp-gmic

apt install -y inkscape blender gimp gimp-plugin-registry darktable krita
apt install -y kolourpaint4 pencil2d pinta tupi karbon mypaint mypaint-data-extras

########### It has depreciation problems
#### BIMP for batch jobs in GIMP
#apt install -y libgimp2.0-dev libpcre3-dev
#cd /var/local/vrk/donjon
#git clone https://github.com/alessandrofrancesconi/gimp-plugin-bimp.git
#cd gimp-plugin-bimp
#ake && make install-admin
#cd /var/local/vrk/donjon
#rm -R gimp-plugin-bimp

echo "
Graphic design done. Media stuff, VLC, audio players, Kdenlive...
"
apt install -y vlc vlc-data browser-plugin-vlc mplayer2 clementine amarok kdenlive rhythmbox
echo "
Media done. Audiophile tools, Audacity, LMMS, Kid3 audio tag tool...
"
apt install -y audacity lmms kid3
echo "Sound's great. (hehe) Getting desktop goodies...
"
apt install -y ubuntu-restricted-extras alsa-oss libasound2 libasound2-plugins
apt install -y gnome-music gnome-photos dia-gnome planner gromit gnome-chess
echo "
Got the goodies. Sky time... Stellarium...
"
apt install -y stellarium

#
#echo "
#Now doing Skype...
#"
#apt install -y skype
#echo "
#You got Skype.
#"

## MyPaint
#if [ "${PROCVNO}" = "amd64" ]; then
#/var/local/vrk/boss/install-mypaint64
#fi
#if [ "${PROCVNO}" = "i386" ]; then
#apt install -y mypaint mypaint-data-extras
#fi


# Set config
echo "VUBUNTU_STUDIOLITE_INSTALLED=\"YES\"" >> /var/local/vrk/machineinfo
echo "#!/bin/sh
# Pydio repo status

STUDIOLITE=\"INSTALLED\"
" > /home/${SUDO_USER}/.vrk/configs/studiolitestatus
## Remove repo temp progress files
rm /var/local/vrk/.vubuntu-studiolite-*

# Cleanup
apt autoremove -y

# Finish
echo "
Vubuntu Studio Lite is all set.
"

