#!/bin/sh
#inkVerbBoss! verb.ink

# This installs xscreensvaer and Really Slick Screensavers (rss) and gets it all properly set up

# How to use:
## sudo install-screensavers


# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-screensavers
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-screensavers
"
exit 22; fi

# Check status
. /opt/vrk/machineinfo
if [ "${XSCREENSAVERS_RSS_INSTALLED}" = "YES" ]; then
echo "xscreensaver & Really Slick Screensavers already installed."
exit 0; fi


# Install
apt install -y xscreensaver xscreensaver-gl-extra xscreensaver-data-extra
apt install -y rss-glx
wait
killall xscreensaver
wait
rss-glx_install

# Config
echo "XSCREENSAVERS_RSS_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo
touch /opt/vrk/.xscreensaverrss

# Finish
apt autoremove -y
echo "xscreensaver & Really Slick Screensavers now installed, but not automatically running yet. Manage in:

Apps/Start > Screensaver
"

