#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This installs Google Earth

# How to use:
## sudo ./install-googleearth


# Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./install-googleearth
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-googleearth
"
exit 22; fi


# Install
if [ "${PROCVNO}" = "amd64" ]; then
 if [ ! -f "/var/local/vrk/.vubuntu-studiolite-earth64" ]; then
rm -f google-earth-stable_current_amd64.deb*
wget https://dl.google.com/dl/earth/client/current/google-earth-stable_current_amd64.deb
dpkg -i google-earth-stable*.deb
apt install -yf
rm -f google-earth-stable_current_amd64.deb*
touch /var/local/vrk/.vubuntu-studiolite-earth64
 fi
fi
if [ "${PROCVNO}" = "i386" ]; then
 if [ ! -f "/var/local/vrk/.vubuntu-studiolite-earth386" ]; then
rm -f google-earth-stable_current_i386.deb*
wget https://dl.google.com/dl/earth/client/current/google-earth-stable_current_i386.deb
dpkg -i google-earth-stable*.deb
apt install -yf
rm -f google-earth-stable_current_i386.deb*
touch /var/local/vrk/.vubuntu-studiolite-earth386
 fi
fi


# Finish
apt autoremove -y
echo "Google Earth installed.
"

