#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This installs Nextcloud

# How to use:
## sudo bash install-nextcloud


# Check if installed
if [ ! -f /home/${SUDO_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See READ.ME"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo bash install-nextcloud
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./install-nextcloud
"
exit 22
fi

# Check status
if [ -f /home/${SUDO_USER}/.vrk/configs/nextcloudstatus ]; then
. /home/${SUDO_USER}/.vrk/configs/nextcloudstatus
if [ "${NCSTATUS}" = "INSTALLED" ]; then
echo "Nextcloud already installed. Nothing to do."
exit 0; fi
fi

# Install
if [ ! -f "/var/local/vrk/.vubuntu-nextcloud" ]; then
add-apt-repository ppa:nextcloud-devs/client -y
touch /var/local/vrk/.vubuntu-nextcloud
fi
apt update
apt install nextcloud-client -y

# Config
echo "#!/bin/sh
# Nextcloud repo status

NCSTATUS=\"INSTALLED\"
" > /home/${SUDO_USER}/.vrk/configs/nextcloudstatus

# Finish
apt autoremove -y
rm /var/local/vrk/.vubuntu-nextcloud
echo "Nextcloud should now be installed to the newest version.
"

