#!/bin/sh
#inkVerbBoss! verb.ink

# This backs up basic network configurations and passwords to .vrk/configs
## This is intended to be run before usbbackup

# How to use:
## sudo netbackup


THEMENAME=$1

# Set user
if [ -z "$1" ]; then
VRK_USER=${SUDO_USER}
else
VRK_USER=$1
fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo netbackup
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo netbackup
"
exit 22
fi

# WiFi profiles, VPN, and such
if [ -d /etc/NetworkManager ]; then
mkdir /home/${SUDO_USER}/.vrk/configs/net
cp -R /etc/NetworkManager /home/${SUDO_USER}/.vrk/configs/net
else
echo "Network settings folder doesn't exist. You may need to get those manually, if you want them.
Check:
/etc/network/interfaces
/etc/wpa_supplicant.conf
.gconf/system/networking/
or use Google to figure out what's going on."
fi

