#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This sets a sudo/root desktop theme, only for the current desktop session, for desktop apps run as sudo/root

# How to use:
## sudo ./sudotheme [Theme-Name]

## Use NOTE:  Type the name just as it appears in Tweak > Themes; spaces require "Quotes Around" the name.


THEMENAME=$1

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./sudotheme [Theme-Name]
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./sudotheme [Theme-Name]
"
exit 22
fi

gsettings set org.gnome.desktop.interface gtk-theme "${THEMENAME}"

