#!/bin/sh
#inkVerbBoss! verb.ink

# This updates all themes and icons (included and extra) via Git and installs them overtop of old versions of the same files linked to /usr/share
## This also adds existing archives of the Libra theme and Ultra-Flat icons, which rarely change and are not available via Git.

# "Upstall" means "update or install".

# How to use:
## sudo ./themicons-git-upstall


INSTHEMICON=$1

# Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./themicons-git-upstall
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./themicons-git-upstall
"
exit 22; fi

# Include the config
. /var/local/vrk/machineinfo


# Theme check #
if [ "$LINUX_DISTRO" = "ubuntu" ] || [ "$LINUX_DISTRO" = "gnome" ]; then

# Prepare notice
echo "
This only installs Adapta, Arc, and Vertex themes!

Any others must be specified like so:

sudo ./themicons-git-upstall adapta
sudo ./themicons-git-upstall arc
sudo ./themicons-git-upstall blackbird
sudo ./themicons-git-upstall blumix
sudo ./themicons-git-upstall flatabulous
sudo ./themicons-git-upstall vertex

"
sleep 4

echo "Installing now.

Grab some tea. This is gonna' take a while...
"

# Themes
rm -rf /var/local/vrk/donjon/ti/themes-
mkdir -p /var/local/vrk/donjon/ti/themes-
cd /var/local/vrk/donjon/ti/themes-

## Adapta
if [ -z "${1}" ] || [ "${INSTHEMICON}" = "adapta" ] ; then
git clone https://github.com/adapta-project/adapta-gtk-theme
cd adapta-gtk-theme
./autogen.sh
make
rm -rf /usr/share/themes/Adapta*
make install
cd ..
rm -rf adapta-gtk-theme
fi

## Arc
if [ -z "${1}" ] || [ "${INSTHEMICON}" = "arc" ] ; then
git clone https://github.com/horst3180/arc-theme
cd arc-theme
./autogen.sh --prefix=/usr
rm -rf /usr/share/themes/Arc*
make install
cd ..
rm -rf arc-theme
fi

## Blackbird
if [ "${INSTHEMICON}" = "blackbird" ]; then
git clone https://github.com/shimmerproject/Blackbird
cd Blackbird
./autogen.sh
make install
cd ..
rm -rf Blackbird
fi

## Blumix
if [ "${INSTHEMICON}" = "blumix" ]; then
git clone https://github.com/rhoconlinux/Blumix
cd Blumix
rm -rf /usr/share/themes/Blumix*
mv Blumix /usr/share/themes/
cd ..
rm -rf Blumix
fi

## Flatabulous
if [ "${INSTHEMICON}" = "flatabulous" ]; then
git clone https://github.com/anmoljagetia/Flatabulous
rm -rf /usr/share/themes/Flatabulous
mv Flatabulous /usr/share/themes/
fi

## Vertex
if [ -z "${1}" ] || [ "${INSTHEMICON}" = "vertex" ]; then
git clone https://github.com/horst3180/vertex-theme
cd vertex-theme
./autogen.sh --prefix=/usr
rm -rf /usr/share/themes/Vertex*
make install
cd ..
rm -rf vertex-theme
fi

## Clean up
cd ../
rm -rf themes-

# Theme check #
fi


# Prepare notice
echo "
This only installs Surfin icons!

Any others must be specified like so:

sudo ./themicons-git-upstall surfn
sudo ./themicons-git-upstall numix
sudo ./themicons-git-upstall moka
"
sleep 4


# Icons
mkdir -p /var/local/vrk/donjon/ti/icons-
cd /var/local/vrk/donjon/ti/icons-

## Surfn
if [ -z "${1}" ] || [ "${INSTHEMICON}" = "surfn" ]; then
git clone https://github.com/erikdubois/Surfn
cd Surfn
rm -rf /usr/share/icons/Surfn*
mv Surfn* /usr/share/icons/
### Update
cd /usr/share/icons
for SURFN in Surfn*; do
 if [ -d "${SURFN}" ]; then
 gtk-update-icon-cache /usr/share/icons/${SURFN}
 fi
done
fi

## Numix & Numix Circle
if [ "${INSTHEMICON}" = "numix" ]; then
git clone https://github.com/numixproject/numix-icon-theme
git clone https://github.com/numixproject/numix-icon-theme-circle
rm -rf /usr/share/icons/Numix*
cd numix-icon-theme
mv Numix* /usr/share/icons/
cd ../numix-icon-theme-circle
mv Numix-Circle* /usr/share/icons/
### Update
cd /usr/share/icons
for NUMXIC in Numix*; do
 if [ -d "${NUMXIC}" ]; then
 gtk-update-icon-cache /usr/share/icons/${NUMXIC}
 fi
done
fi

## Moka Icons
if [ "${INSTHEMICON}" = "moka" ]; then
cd /var/local/vrk/donjon/ti/icons-
git clone https://github.com/snwh/moka-icon-theme
cd moka-icon-theme
./autogen.sh
rm -rf /usr/share/icons/Moka*
mv Moka /usr/share/icons/
cd ..
rm -rf moka-icon-theme
### Update
gtk-update-icon-cache /usr/share/icons/Moka/
fi

## Clean up
cd /var/local/vrk
rm -rf /var/local/vrk/donjon/ti/icons-


# Finish
echo "Themes and icons updated, cap'n."
