#!/bin/sh
#inkVerbBoss! verb.ink

# This updates all themes and icons (included and extra) via Git and installs them overtop of old versions of the same files linked to /usr/share
## This also adds existing archives of the Libra theme and Ultra-Flat icons, which rarely change and are not available via Git.

# "Upstall" means "update or install".

# How to use:
## sudo ./themicons-git-upstall


INSTHEMICON=$1

# Set user
if [ -z "$1" ]; then
VRK_USER=${SUDO_USER}
else
VRK_USER=$1
fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./themicons-git-upstall
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./themicons-git-upstall
"
exit 22
fi

# Prepare notice
echo "
This only installs Arc themes and Surfin icons!

Any others must be specified like so:

Themes: 
sudo ./themicons-git-upstall adapta
sudo ./themicons-git-upstall arc
sudo ./themicons-git-upstall blumix
sudo ./themicons-git-upstall flatabulous
sudo ./themicons-git-upstall vertex

Icons:
sudo ./themicons-git-upstall surfn
sudo ./themicons-git-upstall moka
"
sleep 4

echo "Installing now.

Grab some tea. This is gonna' take a while...
"

# Themes
rm -rf /var/local/vrk/donjon/ti/themes-
mkdir -p /var/local/vrk/donjon/ti/themes-
cd /var/local/vrk/donjon/ti/themes-

## Adapta
if [ "${INSTHEMICON}" = "adapta" ]; then
git clone https://github.com/adapta-project/adapta-gtk-theme
cd adapta-gtk-theme
./autogen.sh
make
rm -rf /usr/share/themes/Adapta*
make install
cd ..
rm -rf adapta-gtk-theme
fi

## Arc
if [ -z "${1}" ] || [ "${INSTHEMICON}" = "arc" ]; then
git clone https://github.com/horst3180/arc-theme
cd arc-theme
./autogen.sh --prefix=/usr
rm -rf /usr/share/themes/Arc*
make install
cd ..
rm -rf arc-theme
fi

## Blumix
if [ "${INSTHEMICON}" = "blumix" ]; then
git clone https://github.com/rhoconlinux/Blumix
cd Blumix
rm -rf /usr/share/themes/Blumix*
mv Blumix /usr/share/themes/
cd ..
rm -rf Blumix
fi

## Flatabulous
if [ "${INSTHEMICON}" = "flatabulous" ]; then
git clone https://github.com/anmoljagetia/Flatabulous
rm -rf /usr/share/themes/Flatabulous
mv Flatabulous /usr/share/themes/
fi

## Vertex
if [ "${INSTHEMICON}" = "vertex" ]; then
git clone https://github.com/horst3180/vertex-theme
cd vertex-theme
./autogen.sh --prefix=/usr
rm -rf /usr/share/themes/Vertex*
make install
cd ..
rm -rf vertex-theme
fi

## Clean up
cd ../
rm -rf themes-


# Icons
mkdir /var/local/vrk/donjon/ti/icons-
cd /var/local/vrk/donjon/ti/icons-

## Surfn
if [ -z "${1}" ] || [ "${INSTHEMICON}" = "surfn" ]; then
git clone https://github.com/erikdubois/Surfn
cd Surfn
mv Surfn* /usr/share/icons/
### Update
cd /usr/share/icons
for SURFN in Surfn*; do
 if [ -d "${SURFN}" ]; then
 gtk-update-icon-cache /usr/share/icons/${SURFN}
 fi
done
fi

## Moka Icons
if [ "${INSTHEMICON}" = "moka" ]; then
cd /var/local/vrk/donjon/ti/icons-
git clone https://github.com/snwh/moka-icon-theme
cd moka-icon-theme
#./autogen.sh
rm -rf /usr/share/icons/Moka*
mv Moka /usr/share/icons/
cd ..
rm -rf moka-icon-theme
### Update
gtk-update-icon-cache /usr/share/icons/Moka/
fi

## Clean up
cd /var/local/vrk
rm -rf /var/local/vrk/donjon/ti/icons-


# Finish
echo "Themes and icons updated, cap'n."

