#!/bin/sh
#inkVerbBoss! verb.ink
set -e

# This uninstalls Vrk Station folder and all settings from a user's home

# How to use:
## sudo ./uninstall-vrk

# How to use on your local computer for another, non-sudo user:
## sudo ./uninstall-vrk [user]

# NOTE: If you run this for yourself without a [user] declaration, then your .vrk folder will have a "boss" folder link.


# Set user
if [ -z "$1" ]; then
VRK_USER=${SUDO_USER}
else
VRK_USER=$1
fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./uninstall-vrk
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./uninstall-vrk
"
exit 22
fi

# Logout warning
if [ -z $1 ]; then
echo "
!! IMPORTANT !!

You are about to lose all your Vubuntu Vrk Station settings, including any gosurfers. Normal Ubuntu apps and desktop themes will NOT be uninstalled.

When this finishes, you will be logged out and the computer will reboot. Close all apps and get ready...

Are you ready to continue, then logout and reboot? Type \"yes\" to continue."
read LOGOUTYES
 if [ ${LOGOUTYES} != "yes" ]; then
echo "Exiting, not finished. You can run this again anytime via:
cd /var/local/vrk/boss
sudo ./uninstall-vrk
"
exit 0
 fi
fi

# Include configs
. /home/${VRK_USER}/.vrk/configs/lang/stationuser-dirs_INITIAL
. /home/${VRK_USER}/.vrk/configs/lang/stationuser-dirs_EN
. /home/${VRK_USER}/.vrk/configs/stationinfo

# Put folders back from cloud
if [ "${VRK_CLOUD_DIR}" = "NOT_SET" ]; then
echo "No cloud... Okay."
else
## Put directories back where links were
### Documents
 if [ -L /home/${VRK_USER}/"${VRK_DOCUMENTS_DIR}" ]; then
  if [ -d /home/${VRK_USER}/${VRK_CLOUD_DIR}/Vrk/"${VRK_DOCUMENTS_DIR}" ]; then
rm -f /home/${VRK_USER}/"${VRK_DOCUMENTS_DIR}"
cp -R /home/${VRK_USER}/${VRK_CLOUD_DIR}/Vrk/"${VRK_DOCUMENTS_DIR}" /home/${VRK_USER}/
chown -R ${VRK_USER} /home/${VRK_USER}/${VRK_DOCUMENTS_DIR}
  fi
 fi
### Templates
 if [ -L /home/${VRK_USER}/"${VRK_TEMPLATES_DIR}" ]; then
   if [ -d /home/${VRK_USER}/${VRK_CLOUD_DIR}/Vrk/"${VRK_TEMPLATES_DIR}" ]; then
rm -f /home/${VRK_USER}/"${VRK_TEMPLATES_DIR}"
cp -R /home/${VRK_USER}/${VRK_CLOUD_DIR}/Vrk/"${VRK_TEMPLATES_DIR}" /home/${VRK_USER}/
chown -R ${VRK_USER} /home/${VRK_USER}/${VRK_TEMPLATES_DIR}
  fi
 fi
### Work folder
 if [ -L /home/${VRK_USER}/"${VRK_WORK_DIR}" ]; then
  if [ -d /home/${VRK_USER}/${VRK_CLOUD_DIR}/Vrk/"${VRK_WORK_DIR}" ]; then
rm -f /home/${VRK_USER}/"${VRK_WORK_DIR}"
cp -R /home/${VRK_USER}/${VRK_CLOUD_DIR}/Vrk/"${VRK_WORK_DIR}" /home/${VRK_USER}/
chown -R ${VRK_USER} /home/${VRK_USER}/${VRK_WORK_DIR}
  fi
 fi
fi

# Original language home directories
if [ -d /home/${VRK_USER}/"${VRK_DESKTOP_DIR}" ] && [ ! -d /home/${VRK_USER}/"${XDG_DESKTOP_DIR}" ]; then
	mv /home/${VRK_USER}/"${VRK_DESKTOP_DIR}" /home/${VRK_USER}/"${XDG_DESKTOP_DIR}"
fi
if [ -d /home/${VRK_USER}/"${VRK_DOWNLOAD_DIR}" ] && [ ! -d /home/${VRK_USER}/"${XDG_DOWNLOAD_DIR}" ]; then
	mv /home/${VRK_USER}/"${VRK_DOWNLOAD_DIR}" /home/${VRK_USER}/"${XDG_DOWNLOAD_DIR}"
fi
if [ -d /home/${VRK_USER}/"${VRK_TEMPLATES_DIR}" ] && [ ! -d /home/${VRK_USER}/"${XDG_TEMPLATES_DIR}" ]; then
	mv /home/${VRK_USER}/"${VRK_TEMPLATES_DIR}" /home/${VRK_USER}/"${XDG_TEMPLATES_DIR}"
fi
if [ -d /home/${VRK_USER}/${VRK_PUBLICSHARE_DIR} ] && [ ! -d /home/${VRK_USER}/${XDG_PUBLICSHARE_DIR} ]; then
	mv /home/${VRK_USER}/${VRK_PUBLICSHARE_DIR} /home/${VRK_USER}/"${XDG_PUBLICSHARE_DIR}"
fi
if [ -d /home/${VRK_USER}/"${VRK_DOCUMENTS_DIR}" ] && [ ! -d /home/${VRK_USER}/"${XDG_DOCUMENTS_DIR}" ]; then
	mv /home/${VRK_USER}/"${VRK_DOCUMENTS_DIR}" /home/${VRK_USER}/"${XDG_DOCUMENTS_DIR}"
fi
if [ -d /home/${VRK_USER}/"${VRK_MUSIC_DIR}" ] && [ ! -d /home/${VRK_USER}/"${XDG_MUSIC_DIR}" ]; then
	mv /home/${VRK_USER}/"${VRK_MUSIC_DIR}" /home/${VRK_USER}/"${XDG_MUSIC_DIR}"
fi
if [ -d /home/${VRK_USER}/"${VRK_PICTURES_DIR}" ] && [ ! -d /home/${VRK_USER}/"${XDG_PICTURES_DIR}" ]; then
	mv /home/${VRK_USER}/"${VRK_PICTURES_DIR}" /home/${VRK_USER}/"${XDG_PICTURES_DIR}"
fi
if [ -d /home/${VRK_USER}/"${VRK_VIDEOS_DIR}" ] && [ ! -d /home/${VRK_USER}/"${XDG_VIDEOS_DIR}" ]; then
	mv /home/${VRK_USER}/"${VRK_VIDEOS_DIR}" /home/${VRK_USER}/"${XDG_VIDEOS_DIR}"
fi
rm -rf /home/${VRK_USER}/myLang
cp /home/${VRK_USER}/.config/user-dirs.dirs.ink-bak /home/${VRK_USER}/.config/user-dirs.dirs

# Remove myWall wallpapers
## KDE, Budgie & Global
rm -rf /home/${VRK_USER}/.local/share/backgrounds/myWall
## GNOME
rm -rf /home/${VRK_USER}/.local/share/gnome-background-properties/my-wall.xml
## Xfce
rm -rf /home/${VRK_USER}/.config/xfce4
## MATE
rm -rf /home/${VRK_USER}/.local/share/mate-background-properties/my-mate-wall.xml
## Cinnamon
rm -rf /home/${VRK_USER}/.local/share/cinnamon-background-properties/my-cinn-wall.xml

# Remove installation
rm -rf /home/${VRK_USER}/.vrk

# Finish
echo "Sayonara. Vrk Station uninstalled from ${VRK_USER}."

