#!/bin/bash

# This adds droids from a git repo.

# How to use:
## vdroid [ http://github.com/clonePathTo/droidRepo - optional to avoid dialogue ]

# Eg:
## sudo vdroid 
## sudo vdroid https://github.com/inkVerb/droids


# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo vdroid
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo vdroid
"
exit 22
fi

# Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check variables
if [ -z "$1" ]; then
echo "What is the clone repo URL?"
read DROIDREPO
else
DROIDREPO=$1
fi

# Sanitize repo
CLNDROIDREPO1=$(echo $DROIDREPO | cut -d'/' -f5-)
CLNDROIDREPO=$(echo $CLNDROIDREPO1 | sed 's/\.git//')

# Clone it
cd /var/local/vrk/droids
git clone ${DROIDREPO}

# Clean up and install
cd ${CLNDROIDREPO}
chmod +x vd*
mv vd* ../
cd ..
rm -rf ${CLNDROIDREPO}

# Finish
echo "The droids from \"${CLNDROIDREPO}\" are installed."


