#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This refreshes the Vrk tools (boss, surf, donjon) in .vrk from /var/local/vrk

# How to use:
## sudo ./vrkfresh [user - if not current sudoer]


# Set user
if [ -z "$1" ]; then
VRK_USER=${SUDO_USER}
else
VRK_USER=$1
fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./vrkfresh
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./vrkfresh
"
exit 22
fi

# Include the config
. /home/${VRK_USER}/.vrk/configs/stationinfo

# Refresh the user directory
## For any user
mkdir -p /home/${VRK_USER}/.vrk/boards
rm -rf  /home/${VRK_USER}/.vrk/boards/*
cp /var/local/vrk/droids/* /home/${VRK_USER}/.vrk/boards/
cp /var/local/vrk/surf/* /home/${VRK_USER}/.vrk/boards/
if [ -L "/home/${VRK_USER}/.vrk/donjon" ]; then
rm -f /home/${VRK_USER}/.vrk/donjon
fi
ln -sfn /var/local/vrk/donjon /home/${VRK_USER}/.vrk/
mkdir -p /home/${VRK_USER}/.vrk/go
## For a sudoer
if [ "${USER_BOSSYN}" = "CAN_BOSS" ]; then
ln -sfn /var/local/vrk/boss/* /home/${VRK_USER}/.vrk/boards/
fi
## Own
chown -R ${VRK_USER} /home/${VRK_USER}/.vrk

# Finish
echo "Vrk tools are up-to-date for ${VRK_USER}."

