#!/bin/sh
# inkVerbSurfer, verb.ink
set -e

# This sets the settings for this Vrk Station to be an inkNet Client to CA Verber
## This can be run to update an existing config

# How to use:
## inknetmakevrkclient [Vrk IP - if known]

# Eg:
## inknetmakevrkclient
## inknetmakevrkclient 999.999.99.999


# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

if [ -z "$1" ]; then
ADDIP="NOT_SET"
fi
ADDTHISHOST="$(hostname -f)"
SCORENHOSTNAME="$(echo ${ADDTHISHOST} | sed 's/\./_/g')"
ADDUSER="${USER}"
ADDCLIENTNAME="${ADDUSER}_${SCORENHOSTNAME}"

echo "#!/bin/sh
# inkNet config, verb.ink
## This contains information about this Client Vrk Station's credentials used in signing SSH keys for inkNet on a CA Verber
## Note that a local Vrk Station only uses the local username as the URI for SSH key and cert purposes

CLIENTMACHINE=\"${ADDTHISHOST}\"
CLIENTNAME=\"${ADDCLIENTNAME}\"
CLIENTIP=\"${ADDIP}\"
CLIENTUSER=\"${ADDUSER}\"
" > ~/.vrk/configs/inknet/client.vrk.cnf

# Finish
echo "This user account is now ready to become a Client to Verbers.

Verbers will know this machine's user account as: ${ADDCLIENTNAME}
"

