#!/bin/sh
# inkVerbSurfer, verb.ink
set -e

# This sets up and installs inkNet and various inkVerb dependencies for a Vrk Station
## It is not the only way, this just makes it simple to connect to the first Verber
## This can be interactive if credentials are not entered first

# How to use:
## inknetinstall [Verber host] [Verber IP] [Vrk IP - if known]

# Eg:
## inknetinstall joey1.joey.verb.ink 999.999.411.199
## inknetinstall joey1.joey.verb.ink 999.999.411.199 333.333.333.333


VHOST=$1
VIP=$2
CIP=$3

# Prepare the Vrk Station as a Client
if [ ! -f ~/.vrk/configs/inknet/client.vrk.cnf ]; then
 if [ -z "$3" ]; then
echo "If you know your Vrk Station's IP, you may enter it here. Otherwise, just press Enter.
You can change this anytime via inknetmakevrkclient
"
read ECIP
  if [ -z "${ECIP}" ]; then
CIP="NOT_SET"
  else
CIP=${ECIP}
  fi
 fi
~/.vrk/boards/inknetmakevrkclient ${CIP}
fi
if [ -f ~/.vrk/configs/inknet/client.vrk.cnf ]; then
echo "Already set-up as a Client..."
fi

# Add the CA Verber profile
if [ -z $3 ] && [ ! -f ~/.vrk/configs/inknet/verbers/verber.*.cnf ]; then
echo " Enter the Verber host, such as \"john1.john.verb.ink\""
read EVNAME
if [ -z "${EVNAME}" ]; then
echo "Nothing entered. I quit."; exit 22; fi
echo " Enter the Verber IP Address with dots and all, ie: 777.06.55.4321"
read EVIP
if [ -z "${EVIP}" ]; then
echo "Nothing entered. I quit."; exit 22; fi
VHOST=${EVNAME}
VIP=${EVIP}
~/.vrk/boards/inknetaddverber ${VHOST} ${VIP}
## Add the Verber's Cert
echo "Getting the latest cert from this Verber..."
~/.vrk/boards/inknetaddcaverberpubkey ${VHOST}
fi
if [ -n $2 ]
~/.vrk/boards/inknetaddverber ${VHOST} ${VIP}
## Add the Verber's Cert
echo "Getting the latest cert from this Verber..."
VERBERNAME=${VNAME}_verb_${VTLD}
~/.vrk/boards/inknetaddcaverberpubkey ${VERBERNAME}
fi
if [ -z $2 ] && [ -f ~/.vrk/configs/inknet/verbers/verber.*.cnf ]
echo "This Vrk Station is already configured for at least one Verber. If you want to add another or update the Verber's IP, run this again like this:
inknetinstall [Verber host - ie: joey1.joey.verb.ink ] [Verber ip]
"
fi

# Finish
. ~/.vrk/configs/inknet/client.vrk.cnf
## If there is no key yet
if [ ! -f ~/.ssh/in_cli_${CLIENTNAME}_key ]; then
~/.vrk/boards/inknetnewvrkclientkey
exit 0
else
## If there is a key
echo "Ready for the next step...
"
~/.vrk/boards/showinknetkey
fi

