#!/bin/sh
# inkVerbSurfer, verb.ink
set -e

# This adds a Verber Client for this inkNet CA Verber to host
## This can be run to update an existing Verber's IP

# How to use:
## inknetaddverber [Verber host] [Verber IP]

# Eg:
## inknetaddverber john1.john.verb.ink 999.999.99.999
## inknetaddverber john1.ink.inkisaberb.com 999.999.99.999 (For Domain Mod)


ADDVERBERHOST=$1
ADDVERBERNAME="$(echo ${ADDVERBERHOST} | sed 's/\./_/g')"
ADDVERBERURI="$(echo ${ADDVERBERHOST} | rev | cut -d'.' -f-3 | rev)"
ADDIP="$2"

# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check variables
if [ -z $2 ]; then
echo "You need to specify stuff, like this:
inknetaddverber [Verber host ] [Verber IP]
"
exit 55; fi

# Check if a config for this Verber already exists
if [ -f "~/.vrk/configs/inknet/verbers/verber.${ADDVERBERNAME}.cnf" ]; then
echo "A config for this Verber already exists. Do you want to continue and update it?
Type \"y\" and enter to continue..."
read YN
 if [ "${YN}" != "y" ]; then
 echo "Not continuing."; exit 55; fi
fi

# Set the config profile
echo "#!/bin/sh
# inkNet config, verb.ink
## This contains information about a Verber Client's credentials used in signing SSH keys for inkNet on this CA Verber

VERBERHOST=\"${ADDVERBERHOST}\"
VERBERURI=\"${ADDVERBERURI}\"
VERBERNAME=\"${ADDVERBERNAME}\"
VERBERIP=\"${ADDIP}\"
" > ~/.vrk/configs/inknet/verbers/verber.${ADDVERBERNAME}.cnf

# Finish
echo "
All set. You just added the Verber ${ADDVERBERHOST}.
"

