#!/bin/sh
#inkVerbSurfer! verb.ink

# This sets the Vubuntu Desktop preferences for a Vubuntu installation.
## Prerequesite: Vrk™ must be installed

# How to use:
## set-vrk-desktop


# Set
## Vall room
VALL_ROOM="vubuntu"
## Vall background
VALL_BACKGRND="Get-to-Vrk.png"
## Vall lockscreen
VALL_LOCKSRN="inkVerb-Carbon.png"

# Check to make sure this not run as sudo or root
if [ "$(id -u)" = "0" ]; then
echo "Do not run as root or sudo."; exit 22
fi

# Check if Vrk installed on this machine
if [ ! -f /var/local/vrk/machineinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check if Vrk installed to user
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "First, run install-vrk for this user. See README.md"; exit 22
fi

# Check if Vubuntu Desktop installed on the machine
if [ ! -f /var/local/vrk/.vubuntu-desktop-installed ]; then
echo "Vubuntu Desktop hasn't been installed by any user on this machine.
A Superuser/Sudoer needs to run install-vubuntu-desktop for this machine. See README.md"; exit 22
fi

# Check if Vubuntu Desktop is already set for this user
. ~/.vrk/configs/stationinfo
if [ "${VUBUNTU_DESKTOP_SET}" = "YES" ]; then
echo "Vubuntu Desktop already set for this user.

Type \"yes\" to run it again and reset, anything else to quit...
"
read YESRESET
 if [ "${YESRESET}" != "yes" ]; then
exit 0
 fi
fi

# Include the config
. /var/local/vrk/machineinfo

# Kill conflicting apps
killall -q dolphin
killall -q docky

# Global exceptions tests
if [ "$LINUX_DISTRO" = "ubuntu" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DISTRO" = "budgie-desktop" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
#if [ "$LINUX_DISTRO" = "gnome" ]; then
#DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DISTRO" = "xubuntu" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DISTRO" = "ubuntustudio" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DISTRO" = "/usr/share/xsessions/plasma" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DISTRO" = "mate" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DISTRO" = "cinnamon" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
if [ "$LINUX_DISTRO" = "xfce" ]; then
DESKTOP_GLOBE="EXCEPTION"; fi
## Needs Docky on side
if [ "$LINUX_DISTRO" = "/usr/share/xsessions/plasma" ]; then
DESKTOP_DOCKY="SIDE"; fi
if [ "$LINUX_DISTRO" = "mate" ]; then
DESKTOP_DOCKY="SIDE"; fi
if [ "$LINUX_DISTRO" = "cinnamon" ]; then
DESKTOP_DOCKY="SIDE"; fi
if [ "$LINUX_DISTRO" = "xfce" ]; then
DESKTOP_DOCKY="SIDE"; fi
#if [ "$LINUX_DISTRO" != "/usr/share/xsessions/plasma" ]; then
#DESKTOP_GLOBE="EXCEPTION"; fi

# Global
## Gedit always opens a new window, not tab-clustering (possible solutions)
#gsettings set org.gnome.gedit.preferences.ui show-tabs-mode 'never'
#echo "alias gedit=\"gedit --new-window\"" >> ~/.bashrc

## Window Snapping
#notyet

## Compose Key: CapsLock key
dconf write /org/gnome/desktop/input-sources/xkb-options "['compose:caps']"
#dconf write /org/gnome/desktop/input-sources/xkb-options "['compose:menu']"

## Alt + Secondary click = resize
if [ -x "$(command -v gconftool)" ]; then
gconftool-2 -s -t bool /apps/metacity/general/resize_with_right_button true; fi
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Alt>'

## Minimize in GNOME Windows
gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar 'minimize'
### Other options to minimize:  maximize toggle-maximize-vertically toggle-maximize-horizontally menu
gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,close'
### Alternative re-order:
#gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'

### Set Background Wallpaper
~/.vrk/boards/set-vall ${VALL_ROOM} ${VALL_BACKGRND}
~/.vrk/boards/set-vall-lock ${VALL_ROOM} ${VALL_LOCKSRN}

## Gedit (may be redundant in per-environments below, but just be safe)
gsettings set org.gnome.gedit.preferences.editor wrap-mode none
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'

## Disable screen lock (which requires password every time after the screen blanks, or double-login on changing user)
gsettings set org.gnome.desktop.screensaver lock-enabled false

## App global configs
### Check prerequesite directories
mkdir -p ~/.config/autostart
#### Just in case, we never know when some update will break the known order
mkdir -p ~/.gconf/apps/
### Autostart
#right now there aren't any global autostarts and the vrk/donjon/global/config/autostart dir doesn't exist.
#cp -rf ~/.vrk/donjon/global/config/autostart ~/.config/
### Kate
cp -rf ~/.vrk/donjon/global/config/katepartrc ~/.config/
### Guake
~/.vrk/boards/set-guake-on
mkdir -p ~/.gconf/apps
if [ ! -d ~/.gconf/apps/guake ]; then
cp -rf ~/.vrk/donjon/global/gconf/apps/guake ~/.gconf/apps/
fi

## App Theming
### Dependency directory
mkdir -p ~/.local/share/applications
### Future: (still doesn't work all the time)
#http://askubuntu.com/questions/78088/can-i-apply-a-different-gtk3-theme-from-the-main-one-to-an-individual-applicatio
# This directory has .css files with app names
#/usr/share/themes/*Theme Name*/gtk-3.0/apps/
# Individual apps
#http://worldofgnome.org/running-gtk-applications-different-themes-per-app/
### LibreOffice (doesn't work in Xfce or GNOME, but works in Unity)
cp /usr/share/applications/libreoffice-writer.desktop ~/.local/share/applications/libreoffice.writer.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Blumix libreoffice --writer %U/g" ~/.local/share/applications/libreoffice.writer.desktop
cp /usr/share/applications/libreoffice-calc.desktop ~/.local/share/applications/libreoffice.calc.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Blumix libreoffice --calc %U/g" ~/.local/share/applications/libreoffice.calc.desktop
cp /usr/share/applications/libreoffice-math.desktop ~/.local/share/applications/libreoffice.math.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Blumix libreoffice --math %U/g" ~/.local/share/applications/libreoffice.math.desktop
cp /usr/share/applications/libreoffice-base.desktop ~/.local/share/applications/libreoffice.base.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Blumix libreoffice --base %U/g" ~/.local/share/applications/libreoffice.base.desktop
cp /usr/share/applications/libreoffice-draw.desktop ~/.local/share/applications/libreoffice.draw.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Blumix libreoffice --draw %U/g" ~/.local/share/applications/libreoffice.draw.desktop
cp /usr/share/applications/libreoffice-impress.desktop ~/.local/share/applications/libreoffice.impress.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Blumix libreoffice --impress %U/g" ~/.local/share/applications/libreoffice.impress.desktop
cp /usr/share/applications/libreoffice-startcenter.desktop ~/.local/share/applications/libreoffice.startcenter.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Blumix libreoffice %U/g" ~/.local/share/applications/libreoffice.startcenter.desktop

## Pause to avoid trouble
sleep 1

# Global #


# Budgie
if [ "$LINUX_DISTRO" = "budgie-desktop" ]; then

## App Defaults
cp ~/.vrk/donjon/global/config/mimeapps.list ~/.config/

## Autostart special
cp -rf ~/.vrk/donjon/budgie/config/autostart ~/.config/

## Flatabulous terminal "profile" (color scheme)
#~/.vrk/donjon/xt-budgie # it uses Terminix, not the gnome terminal

## Set theme
#Budgie's theme is already awesome and other GTK themes don't seem to work well with Budgie
#gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface icon-theme "Surfn-Majestic"
gsettings set org.gnome.desktop.interface cursor-theme "DMZ-Black"

## Make icons work in menues
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ShellShowsAppMenu': <0>, 'Gtk/ButtonImages': <1>, 'Gtk/MenuImages': <1>}"

## LibreOffice theming
### Can be: breeze oxygen tango voffice etc
# reports an error message
#sed -i 's#<item oor:path="/org\.openoffice\.Office\.Common/Misc"><prop oor:name="SymbolStyle" oor:op="fuse"><value>.*</item>#<item oor:path="/org\.openoffice\.Office\.Common/Misc"><prop oor:name="SymbolStyle" oor:op="fuse"><value>voffice</value></prop></item>#g' ~/.config/libreoffice/4/user/registrymodifications.xcu

## Xfdashboard
#https://github.com/gmc-holle/xfdashboard/issues/122
#DEV: This is still in dev here for FYI in 15.04 and may never be necessary

fi
# Budgie #


# Unity
if [ "$LINUX_DISTRO" = "ubuntu" ]; then

## App Defaults
cp -rf ~/.vrk/donjon/global/config/mimeapps.list ~/.config/

## Autostart special
cp -rf ~/.vrk/donjon/unity/config/autostart ~/.config/

## LibreOffice theming
### Can be: breeze oxygen tango voffice etc
sed -i 's#<item oor:path="/org\.openoffice\.Office\.Common/Misc"><prop oor:name="SymbolStyle" oor:op="fuse"><value>.*</item>#<item oor:path="/org\.openoffice\.Office\.Common/Misc"><prop oor:name="SymbolStyle" oor:op="fuse"><value>voffice</value></prop></item>#g' ~/.config/libreoffice/4/user/registrymodifications.xcu

## Workspaces
dconf write /org/compiz/profiles/unity/plugins/core/hsize 2
dconf write /org/compiz/profiles/unity/plugins/core/vsize 2

## Hot corners
### There is no gsettings schema for this. Use this Python script, read its big thanks for his 2-day coding class!
~/.vrk/donjon/vubuntu-unity-hotcorners.py
### Twice to be sure ;-)
~/.vrk/donjon/vubuntu-unity-hotcorners.py

## Launcher autohide, sensitivity, size, etc.
gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ launcher-hide-mode 1
gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ edge-responsiveness 7.
gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ icon-size 28
### To find your launcher shourtcuts for the next command:$ gsettings get com.canonical.Unity.Launcher favorites
gsettings set com.canonical.Unity.Launcher favorites "['application://org.gnome.Nautilus.desktop', 'application://chromium-browser.desktop', 'application://firefox.desktop', 'application://midori.desktop', 'application://gedit.desktop', 'application://libreoffice-writer.desktop', 'application://thunderbird.desktop', 'application://rhythmbox.desktop', 'application://gnome-calculator.desktop', 'application://unity-tweak-tool.desktop', 'application://unity-control-center.desktop', 'unity://running-apps', 'unity://devices']"
#### Multiple monitors, only one Unity launcher
gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ num-launchers 1

## Theme & Icons
#Depreciated?
#gsettings set org.gnome.desktop.wm.preferences theme 'Adapta-Nokto'
gsettings set org.gnome.desktop.interface gtk-theme "Arc-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Surfn-Luv"

### Conky IN DEV
#cd && wget -O .start-conky http://drive.noobslab.com/data/conky/start-conky
#chmod +x .start-conky
#cd && wget -O gotham-noobslab-ugs.zip http://drive.noobslab.com/data/conky/Gotham/gotham-noobslab-ugs.zip
#unzip gotham-noobslab-ugs.zip && rm gotham-noobslab-ugs.zip

fi
# Unity #


# GNOME
if [ "$LINUX_DISTRO" = "gnome" ]; then

## App Defaults
cp -rf ~/.vrk/donjon/global/config/mimeapps.list ~/.config/

## Autostart special
cp -rf ~/.vrk/donjon/gnome/config/autostart ~/.config/

## Flatabulous terminal "profile" (color scheme)
~/.vrk/donjon/xt-gnome

## Set theme & icons
#Depreciated?
#gsettings set org.gnome.desktop.wm.preferences theme 'Arc-Dark'
gsettings set org.gnome.desktop.interface gtk-theme "Arc-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Surfn-Luv"

## Make icons work in menues
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ShellShowsAppMenu': <0>, 'Gtk/ButtonImages': <1>, 'Gtk/MenuImages': <1>}"

## LibreOffice theming
### Can be: breeze oxygen tango voffice etc
sed -i 's#<item oor:path="/org\.openoffice\.Office\.Common/Misc"><prop oor:name="SymbolStyle" oor:op="fuse"><value>.*</item>#<item oor:path="/org\.openoffice\.Office\.Common/Misc"><prop oor:name="SymbolStyle" oor:op="fuse"><value>voffice</value></prop></item>#g' ~/.config/libreoffice/4/user/registrymodifications.xcu

## Launcher
gsettings set org.gnome.shell favorite-apps "['nautilus.desktop', 'chromium-browser.desktop', 'firefox.desktop', 'epiphany.desktop', 'gedit.desktop', 'libreoffice-writer.desktop', 'thunderbird.desktop', 'rhythmbox.desktop', 'gnome-calculator.desktop', 'gnome-tweak-tool.desktop', 'gnome-control-center.desktop']"

## Extensions
#No, use Ctrl + Click instead
#gnome-shell-extension-tool -e launch-new-instance

fi
# GNOME #


# Xfce (Xubuntu & UbuntuStudio)
## Help:
#http://docs.xfce.org/xfce/xfconf/xfconf-query

if [ "${LINUX_DISTRO}" = "xubuntu" ] || [ "${LINUX_DISTRO}" = "ubuntustudio" ] ; then

## App Defaults
cp -rf ~/.vrk/donjon/global/config/mimeapps.list ~/.config/

## Autostart special
cp -rf ~/.vrk/donjon/xfce/config/autostart ~/.config/

## Mouse cursor theme
gsettings set org.gnome.desktop.interface cursor-theme "DMZ-Black"

## Gedit
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'

## Compose Key: CapLock key
xfconf-query -n -c keyboard-layout -p /Default/XkbOptions/Compose -t string -s "compose:caps"
#xfconf-query -n -c keyboard-layout -p /Default/XkbOptions/Compose -t string -s "compose:menu"

## Set theme & icons
#### Theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Greybird"
#### Per distro ;-)
if [ "${LINUX_DISTRO}" = "ubuntustudio" ]; then
xfconf-query -c xsettings -p /Net/IconThemeName -s "Surfn-Arch-Blue"; fi
if [ "${LINUX_DISTRO}" = "xubuntu" ]; then
xfconf-query -c xsettings -p /Net/IconThemeName -s "Surfn-Numix-Misty"; fi

## Whisker menu
### Icon
#### Per distro ;-)
if [ "${LINUX_DISTRO}" = "ubuntustudio" ]; then
sed -i "s/button-icon=.*/button-icon=\/var\/local\/vall\/rooms\/vubuntu\/icons\/inkVerb-disk-blue\.svg/g" ~/.config/xfce4/panel/whiskermenu-1.rc; fi
if [ "${LINUX_DISTRO}" = "xubuntu" ]; then
sed -i "s/button-icon=.*/button-icon=\/var\/local\/vall\/rooms\/vubuntu\/icons\/inkVerb-disk-white\.svg/g" ~/.config/xfce4/panel/whiskermenu-1.rc; fi
#### Show it
sed -i "s/show-button-icon=.*/show-button-icon=true/g" ~/.config/xfce4/panel/whiskermenu-1.rc
### Favorites
sed -i "s/favorites=.*/favorites=exo-file-manager\.desktop,chromium-browser\.desktop,firefox\.desktop,midori\.desktop,gedit\.desktop,libreoffice-writer\.desktop,thunderbird\.desktop,rhythmbox\.desktop,org\.gnome\.Software\.desktop,gnome-calculator\.desktop/g" ~/.config/xfce4/panel/whiskermenu-1.rc
sed -i "s/favorites-in-recent=.*/favorites-in-recent=false/g" ~/.config/xfce4/panel/whiskermenu-1.rc

## Terminal color scheme
~/.vrk/donjon/xt-xfce

## Workspaces & windows
xfconf-query -c xfwm4 -p /general/workspace_count -s 3
xfconf-query -c xfwm4 -p /general/scroll_workspaces -s true
xfconf-query -c xfwm4 -p /general/mousewheel_rollup -s true
xfconf-query -c xfwm4 -p /general/tile_on_move -s true

## Wallpaper
#first one already set by set-vall, but let's spice up the rest, shall we...
#xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s /usr/share/xfce4/backdrops/inkPage.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor1/workspace0/last-image -s /usr/share/xfce4/backdrops/Pen-Black.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor2/workspace0/last-image -s /usr/share/xfce4/backdrops/Whitetype-Ink-Gray.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor3/workspace0/last-image -s /usr/share/xfce4/backdrops/inkCorner.png

## Pause to avoid trouble
sleep 1

## Hot keys
### Menu
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/Super_L" -t string -s 'xfce4-popup-whiskermenu'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/Super_R" -t string -s 'xfce4-popup-whiskermenu'
#can't use <Super> given the above Super_L and Super_R declarations :-(
#xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>z" -t string -s 'xfce4-popup-whiskermenu'
#xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>space" -t string -s 'xfce4-popup-whiskermenu'
### Xfdashboard
#### set for both orders since order matters
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Ctrl><Alt>Super_L" -t string -s 'xfdashboard'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Ctrl><Alt>Super_R" -t string -s 'xfdashboard'
### Window tiling
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Ctrl><Super>Up" -t string -s 'tile_up_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Ctrl><Super>Down" -t string -s 'tile_down_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Ctrl><Super>Left" -t string -s 'tile_left_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Ctrl><Super>Right" -t string -s 'tile_right_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Left" -t string -s 'tile_up_left_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Right" -t string -s 'tile_up_right_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Alt><Super>Left" -t string -s 'tile_down_left_key'
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Alt><Super>Right" -t string -s 'tile_down_right_key'
### Whisker menu

## Pause to avoid trouble
sleep 1

## Xfdashboard
###DEV see available options: xfconf-query -c xfdashboard -lv
#http://xfdashboard.froevel.de/settings.html
#https://github.com/gmc-holle/xfdashboard/issues/122
## Dashboard settings
xfconf-query -n -t bool -c xfdashboard -p /always-launch-new-instance -s false
xfconf-query -n -t bool -c xfdashboard -p /components/applications-view/show-all-apps -s true
xfconf-query -n -t bool -c xfdashboard -p /components/windows-view/scroll-event-changes-workspace -s true
xfconf-query -n -t string -c xfdashboard -p /theme -s xfdashboard-dark
## Enable the hot-corner plugin by adding the hot-corner value to enabled-plugins as a new property
xfconf-query -n -c xfdashboard -p /enabled-plugins -a -t string -s hot-corner
## Enable gnome shell search provider also (this resets all plugins every time)
#xfconf-query -n -c xfdashboard -p /enabled-plugins -a -t string -s hot-corner -t string -s gnome-shell-search-provider
## Settings for hotcorner
xfconf-query -n -t string -c xfdashboard -p /plugins/hot-corner/activation-corner -s XFDASHBOARD_HOT_CORNER_SETTINGS_ACTIVATION_CORNER_TOP_LEFT
xfconf-query -n -t string -c xfdashboard -p /plugins/hot-corner/activation-duration -s 27
xfconf-query -n -t string -c xfdashboard -p /plugins/hot-corner/activation-radius -s 1
## Favorites (spelled British in settings!)
### Defaults:
### xfconf-query -n -t string -c xfdashboard -p /favourites -t string -s "exo-web-browser.desktop" -t string -s "exo-mail-reader.desktop" -t string -s "exo-file-manager.desktop" -t string -s "exo-terminal-emulator.desktop"
### xfconf-query -n -t string -c xfdashboard -p /favourites -t string -s "exo-file-manager.desktop" -t string -s "chromium-browser.desktop" -t string -s "firefox.desktop" -t string -s "gedit.desktop" -t string -s "libreoffice-writer.desktop" -t string -s "gnome-calculator.desktop" -t string -s "xfce4-settings-manager.desktop"
xfconf-query -n -c xfdashboard -p /favourites -t string -s "exo-file-manager.desktop" -t string -s "exo-web-browser.desktop" -t string -s "exo-mail-reader.desktop" -t string -s "gedit.desktop" -t string -s "libreoffice-writer.desktop" -t string -s "gnome-calculator.desktop" -t string -s "xfce4-settings-manager.desktop"

## App Theming (specifically for Xfce since some GTK themes ignore some apps)
### Rhythmbox
cp /usr/share/applications/rhythmbox.desktop ~/.local/share/applications/rhythmbox.desktop
sed -i "s/Exec=.*/Exec=env GTK_THEME=Vertex-Dark rhythmbox %U/g" ~/.local/share/applications/rhythmbox.desktop
### LibreOffice
#### Set bright icons for the dark theme
#### Can be: breeze oxygen etc
#not supported in xubuntu/ubuntustudio
#sed -i 's#<item oor:path="/org\.openoffice\.Office\.Common/Misc"><prop oor:name="SymbolStyle" oor:op="fuse"><value>.*</item>#<item oor:path="/org\.openoffice\.Office\.Common/Misc"><prop oor:name="SymbolStyle" oor:op="fuse"><value>oxygen</value></prop></item>#g' ~/.config/libreoffice/4/user/registrymodifications.xcu

## Message
echo "
Ctrl + Win + Up/Down/Right/Left tiles your window in 1/2 screen.
Shft + Win + Up/Down/Right/Left tiles your window in 1/4 screen on the top.
Alt  + Win + Up/Down/Right/Left tiles your window in 1/4 screen on the bottom.
Ctrl + Win + Alt shows your window spread & dashboard.
Scroll on the desktop to switch workspaces.
"

fi
# Xfce #


# KDE (Mint_KDE & Kubuntu)
if [ "$LINUX_DISTRO" = "/usr/share/xsessions/plasma" ]; then

## App Defaults (KDE, not global)
cp -rf ~/.vrk/donjon/kde/local/share/applications ~/.local/share/

## Autostart special
# Not in KDE

## Settings for Konsole, Dolphin, hotkeys, 4 virtual desktops
cp -rf ~/.vrk/donjon/kde/local/share ~/.local/
cp -rf ~/.vrk/donjon/kde/config/* ~/.config/
sed -i "s/ToolButtonStyle=.*/ToolButtonStyle=IconOnly/g" ~/.config/dolphinrc

## LibreOffice
### Set bright icons for the dark theme
~/.vrk/donjon/libre-theme-dark

fi
# KDE #


# Mint_Cinnamon
if [ "$LINUX_DISTRO" = "cinnamon" ]; then

## App Defaults
# Not in Mint

## Autostart special
# Not in Mint

## Turn off display notifications
gsettings set org.cinnamon.desktop.notifications display-notifications 'false'

## Xed
gsettings set org.x.editor display-line-numbers true
gsettings set org.x.editor color-scheme 'oblivion'

## Gedit
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'

## Theme
### Desktop theme
gsettings set org.cinnamon.theme name "Mint-Y-Dark"
### Controls theme
gsettings set org.cinnamon.desktop.interface gtk-theme "Mint-Y-Dark"
### Window borders theme
gsettings set org.cinnamon.desktop.wm.preferences theme "Mint-Y-Dark"
### Mouse Pointer theme
gsettings set org.cinnamon.desktop.interface cursor-theme "DMZ-Black"
### Icon theme
gsettings set org.cinnamon.desktop.interface icon-theme "Surfn-Majestic"

fi
# Mint_Cinnamon #


# Mint_Xfce
## Currently does not support changing mouse cursor themes
if [ "${LINUX_DISTRO}" = "xfce" ] ; then

## App Defaults
# Not in Mint

## Autostart special
# Not in Mint

## Xed
gsettings set org.x.editor display-line-numbers true
gsettings set org.x.editor color-scheme 'oblivion'

## Gedit
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'

## Theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Mint-Y-Dark"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Surfn-Numix-Misty"

## Wallpaper
#first one already set by set-vall, but let's spice up the rest, shall we...
#xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s /usr/share/xfce4/backdrops/inkPage.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor1/workspace0/last-image -s /usr/share/xfce4/backdrops/Pen-Black.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor2/workspace0/last-image -s /usr/share/xfce4/backdrops/Whitetype-Ink-Gray.png
xfconf-query -n -t string -c xfce4-desktop -p /backdrop/screen0/monitor3/workspace0/last-image -s /usr/share/xfce4/backdrops/inkCorner.png

fi
# Mint_Xfce #


# MATE (& Mint_MATE)
## Currently does not support changing mouse cursor themes
if [ "$LINUX_DISTRO" = "mate" ]; then

## App Defaults
# Not in Mint or MATE

## Autostart special
# Not in Mint or MATE

## Gedit
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'

####### For MATE Pluma text editor (not in Mint)
if [ -x "$(command -v pluma)" ]; then
gsettings set org.mate.pluma color-scheme 'oblivion'
fi
#######

## Dark desktop theme for MATE (not in Mint)
if [ -d "/usr/share/themes/BlackMATE" ]; then
gsettings set org.mate.interface gtk-theme "BlackMATE"
gsettings set org.mate.interface icon-theme "Surfn-Evopop"
else
## Dark desktop theme for Mint_MATE
gsettings set org.mate.interface gtk-theme "Mint-Y-Dark"
gsettings set org.mate.interface icon-theme "Surfn-Numix-Misty"
fi

####### For Mint_MATE Xed text editor (not in MATE)
if [ -x "$(command -v xed)" ]; then
gsettings set org.x.editor display-line-numbers true
gsettings set org.x.editor color-scheme 'oblivion'
fi
#######

fi
# MATE #


# Configs
sed -i "s/VUBUNTU_DESKTOP_SET=.*/VUBUNTU_DESKTOP_SET=\"YES\"/g" ~/.vrk/configs/stationinfo

# Finish
echo "Enjoy Vubuntu Desktop settings. Login again to see them all. :-)
"
sleep 2
