#!/bin/sh
#inkVerbBoss! verb.ink

# This sets GIMP to use hotkeys and layout more familiar to people who know Photoshop

# DISCLAIMER: This is NOT Photoshop and has no intention of copying or pretending to be Photoshop or Adobe!

# Thanks: Michael & doctormo
## Love you Michael Bender, DO MORE VIDEOS!
#https://www.youtube.com/watch?v=zhfs5QyMv5c
## Smart idea, a real need, Photoshop is somewhat of a standard "mo". Thanks, doctormo!
#http://doctormo.deviantart.com/art/Gimp-2-8-Photoshop-Tweaks-432736644
#https://github.com/doctormo/GimpPs

# How to use:
## set-gimp-pscc


# Check to make sure this not run as sudo or root
if [ "$(id -u)" = "0" ]; then
echo "Dude. Don't change this folder as root. None of that sudo stuff here."; exit 22
fi

# Check if Vrk installed on machine
if [ ! -d /opt/vrk ]; then
echo "First, run install-vubuntu-vrkstation for this user. See README.md"; exit 22
fi

# Check if Vrk installed to user
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "First, run install-vubuntu-vrkstation for this user. See README.md"; exit 22
fi

# Disclaimer
echo "I understand that:
- This is not Photoshop.
- Pretending to be Photoshop or Adobe would be wrong and bad and no one here is doing that.
- \"Photoshop\" or \"CC\" or \"Ps\" or \"CreativeCloud\" here, when referred to, mean the awesome, familiar layout and hotkeys used by the great people at Adobe, not any actual product itself.
- I'm not a pirate and if I ever see pirating, I'll let everyone know, including inkVerb at http://vubuntu.info

- This will change my layout and way of using GIMP. To change back, I can use set-gimp-default

Type \"yes\" if you agree and want to set Ps/CC -like styles in GIMP for this user.
"
read CONTINUEYES
if [ "${CONTINUEYES}" != "yes" ]; then
echo "Bye.
"
exit 0
fi

# Git clone & do it
cd ~/
git clone https://github.com/doctormo/GimpPs
mv .gimp-2.8 .gimp-2.8-vBAK
mv GimpPs .gimp-2.8

# Finish
echo "Done. GIMP will not be normal."

