#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This removes guake-indicator from autostart and replaces it with guake

# How to use:
## ./set-guake-on


# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Refresh guake's autostart status for indicator (to avoid duplicate autostarts)
rm -f ~/.config/autostart/guake-indicator.desktop
cp ~/.vrk/donjon/guake/guake.desktop ~/.config/autostart/

# Finish
echo "Guake will load at startup, usually in silence, use F12 ;-)"

