#!/bin/sh
# inkVerb Surfer, verb.ink
set -e

# This shows the inkNet Client key, probably so it can be signed by the CA Verber

# How to use:
## showinknetkey


# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check & include the config
if [ ! -f ~/.vrk/configs/inknet/client.verber.cnf ]; then
echo "This is not yet ready to connect to a Verber via inkNet.

First run inknetmakevrkclient
"
exit 22
fi
~/.vrk/configs/inknet/client.verber.cnf

# Display info
echo "
Client Type: \"verber\"
Client Name: \"${CLIENTNAME}\"
Copy and paste the ENTIRE long key below, as is, into the \"Activate Client key\" area on the inkNet CA Inker:
"
cat ~/.ssh/inknet_client_${CLIENTNAME}_key.pub

