#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This adds an existing surfer's profile to Guake Indicator as a root menu item

# How to use:
## ./ssh-guake-on


# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Refresh guake's autostart status for indicator (to avoid duplicate autostarts)
rm -f ~/.config/autostart/guake-indicator.desktop
## Remember, Budgie needs special autostart *.desktop files
if [ "$DESKTOP_SESSION" = "budgie-desktop" ]; then
cp ~/.vrk/donjon/guake-indicator/budgie/guake.desktop ~/.config/autostart/
else
cp ~/.vrk/donjon/guake-indicator/global/guake.desktop ~/.config/autostart/
fi

# Finish
echo "Guake-Indicator will not at startup, Guake will load instead, usually in silence, use F12 ;-)"

