#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This adds an existing surfer's profile to Guake Indicator as a root menu item

# How to use:
## ./ssh-guake-indicator-on


# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See READ.ME"
exit 22
fi

# Refresh guake's autostart status for indicator (to avoid duplicate autostarts)
rm -f ~/.config/autostart/guake.desktop
## Remember, Budgie needs special autostart *.desktop files
if [ "$DESKTOP_SESSION" = "budgie-desktop" ]; then
cp ~/.vrk/donjon/guake-indicator/budgie/guake-indicator.desktop ~/.config/autostart/
else
cp ~/.vrk/donjon/guake-indicator/global/guake-indicator.desktop ~/.config/autostart/
fi

# Finish
echo "Guake-Indicator is now loading at startup. You can also use F12 for the local \"Earth Guake\" ;-)"

