#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This adds a remote ssh server to Guake Indicator and creates a goSurfer for it

# How to use:
## ./ssh-add-goguake [surfer & menu name] [remote user] [remote IP] [port - optional]


SURFERNAME=$1
USER=$2
IP=$3
PORT=$4

# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check variables
if [ -z $4 ]; then
echo "You need to specify stuff, like this:
ssh-add-goguake [surfer & menu name] [remote user] [remote IP] [port - optional]
"
exit 22
fi

# Assign 22 if [port] option is left empty
if [ -z "${PORT}" ]; then
PORT=22
fi

# Run the surfers
~/.vrk/boards/ssh-add-gosurfer ${SURFERNAME} ${USER} ${IP} ${PORT}
~/.vrk/boards/ssh-add-guake ${SURFERNAME}

