#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This uploads a local SSH key to a surfer's remote server for user no-password login

# How to use:
## ssh-add-key [surfer] [SSH keyname] [password]


GOSURFER=$1
KEYNAME=$2
PASSWORD=$3

# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check variables
if [ -z $3 ]; then
echo "You need to specify stuff, like this:
addfilezillsurfer [surfer] [SSH keyname] [password]
"
exit 22
fi

# Include the config
. ~/.vrk/boards/${GOSURFER}.malibu

# Do it all in one command
cat ~/.ssh/${KEYNAME}.pub | ssh -p ${GOPORT} ${GOUSER}@${GOIP} "mkdir -p ~/.ssh && mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys && reload ssh"
expect "Password:"
send "${PASSWORD}\r"

# Finish
echo "Keys thrown overboard cap'n.

We'll be usin' yer thumbprint from now on.
"

