#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This adds an SSH key to a remote server, enables root no-password login, adds it to Guake Indicator, and creates a Surfer for it
## If the key already exists, then it does not create it. Otherwise it will.
## First, make sure you have logged into your server once, accepted the key fingerprint, and, if you want, changed the port.
### ssh user@IPASSRESS
### nano /etc/ssh/sshd_config # for port

# How to use:
## ssh-add-all [SSH key name] [surfer nickname] [remote user] [remote IP] [remote user password] [port - optional]

# Eg.
## ssh-add-all DO_J nick root 123.456.789.1011 22


KEYNAME=$1
SURFERNAME=$2
USER=$3
IP=$4
PASSWORD=$5
PORT=$6

# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check variables
if [ -z $5 ]; then
echo "You need to specify stuff, like this:
ssh-add-all [SSH key name] [surfer nickname] [remote user] [remote IP] [remote user password] [port - optional]
"
exit 22
fi

# Assign 22 if [port] option is left empty
if [ -z "${PORT}" ]; then
PORT=22
fi

# Run the surfers
if [ ! -f ~/.ssh/${KEYNAME} ]; then
~/.vrk/boards/ssh-craft-key ${KEYNAME}
fi
~/.vrk/boards/ssh-add-goguake ${SURFERNAME} ${USER} ${IP} ${PORT}
~/.vrk/boards/ssh-add-key ${SURFERNAME} ${KEYNAME} ${PASSWORD}
~/.vrk/boards/ssh-filezilla-addkey ${SURFERNAME} ${KEYNAME}
~/.vrk/boards/ssh-guake-indicator-on

