#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This is an interactive script that creates an SSH key locally

# How to use:
## ssh-craft-key [SSH keyname] [passphrase - optional, probably not]


KEYNAME=$1
PASSPHRASE=$2

# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check variables
if [ -z $1 ]; then
echo "You need to specify a key and maybe passphrase (probably not), such as this:
ssh-craft-key My_Computer_Key_icanremember
ssh-craft-key myother_key annooyingpasswordiuseeverytime
"
exit 22; fi

ssh-keygen -t rsa -N "${PASSPHRASE}" -f ~/.ssh/${KEYNAME}

