#!/bin/sh
#inkVerbSurfer! verb.ink
set -e

# This runs diff on all files in two separate directories in the PWD

# How to use:
## vdirdiff [directory 1] [directory 2]


DIR1=$1
DIR2=$2

# Check if installed
if [ ! -f ~/.vrk/configs/.vgitinstdone ]; then
echo "Run vgitinst first."
exit 22
fi

# Check variables
if [ -z "$2" ]; then
 echo "Include directory 1 and 2 like this:
vdirdiff dir1 dir2
"
exit 0
fi

for cmpdrfl in $DIR1/*; do
cmpfl=$(echo $cmpdrfl | sed "s/$DIR1\///")
 if [ -e $DIR2/$cmpfl ]; then
  diff -q $DIR1/$cmpfl $DIR2/$cmpfl
 else
  echo "Does not exist: $DIR2/$cmpfl"
 fi
done

