#!/bin/sh
#inkVerbSurfer! verb.ink

# This tars and xz compresses a directory into a .tar.xz file of the same name

# How to use:
## ./vtar DIRECTORY


TARXZDIR=$1

tar cv "${TARXZDIR}" | xz > "${TARXZDIR}".tar.xz

