#!/bin/bash
#inkVerbDroid! verb.ink

# This Droid removes all broken links in the currend working directory.

# How to use:
## vdkillln [ l - optional to list the current working directory after as a check ]

# Eg:
## vdkillln
## vdkillln l


# Remove the broken links
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done

# Finish
if [ "$1" = "l" ]; then
ls
fi

