#!/bin/sh
#inkVerbDroid! verb.ink &inkVerbSerf!
set -e

# This decompresses a .tvxz file and places its contents in same directory, all in the PWD
## The .vtxz file could simply be renamed to .tar.xz and be used accordingly
## This alternate extention name is intended to prevent tampering and to maintain consistency within inkVerb deployment

# The .vtxz file MUST be in the PWD!
# Do NOT include the .vtxz extension in the filename parameter!

# How to use:
## ./vtxzout [vtxzfile]

# Eg:
## ./vtxzout mystuff


FIL=$1

# Test for a .tar of the same name
if [ -e "${FIL}.tar" ]; then
echo "The file ${FIL}.tar exists, which conflicts with this operation. Deal with that out first."
exit 11; fi

mv ${FIL}.vtxz ${FIL}.tar.xz
xz -d ${FIL}.tar.xz
tar -xf ${FIL}.tar
rm ${FIL}.tar

