#!/bin/sh
#inkVerbMaker! verb.ink
set -e

# This installs Vrk™ on your local system
## This needs some root permissions
## This is not necessaary to run on a Verber/Inker server
## Prerequesite: put vrk in the base of your home folder

# How to use on your local computer:
## sudo ./uninstallvrk [user - if not current sudoer]


# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./uninstallvrk
"
exit 0
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./uninstallvrk
"
exit 0
fi

# Check if present
if [ ! -d "/home/${SUDO_USER}/vrk" ]; then
echo "The vrk folder is not in the right place. I quit."
exit 22
fi

# Set user
if [ -z $1 ]; then
VRK_USER=${SUDO_USER}
else
VRK_USER=$1
fi

# Remove installations for user
chmod +x /home/${SUDO_USER}/vrk/boss/uninstall-vubuntu-vrkstation
/home/${SUDO_USER}/vrk/boss/uninstall-vubuntu-vrkstation ${VRK_USER}

# Remove vrk
rm -rf /var/local/vrk

# Cleanup
rm -rf /home/${SUDO_USER}/vrk

# Finish
echo "Vrk is gone. A few broken links may remain in /usr/share/themes/ and /usr/share/icons/
"

