#!/bin/sh
# inkVerb updater for Vrk™ Station, verb.ink

# This updates the Vrk™ Station
## This contains many version updaters to update a Vrk™ Station sequentially, one version at a time.
## This is run at the path: /var/local/vrk/vrk-update/update

# DEV NOTE: Larger versions must be at the bottom, smaller versions at the top, so "descending"

# Normally this is run automatically by the Boss updatevrk
## Run this if you have downloaded and copied vrk and put it into the home folder
## You must run this per user to update Bosses and Surfers

# How to use:
## cd ~/vrk/inst
## chmod +x upvrk
## sudo ./upvrk


# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./upvrk
"
exit 0
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./upvrk
"
exit 0
fi

# Check if present
if [ ! -d "/home/${SUDO_USER}/vrk" ]; then
echo "The vrk folder is not in the right place. I quit."
exit 22
fi


# Sample version updater:
#UPDATE_PATCH_KVERNO=
#
## Run the update scripts for this patch
#cd /home
#for PATCH_USER in ./*/
#do
#if [ -d "/home/${PATCH_USER}" ]; then
# if [ -f "/home/${PATCH_USER}/.vrk/configs/stationinfo" ]; then
#. /home/${PATCH_USER}/.vrk/configs/stationinfo
#  if [ $(echo "${UPDATE_PATCH_KVERNO}>${USER_KVERNO}"|bc) = 1 ]; then
###### PER-USER PATCH SCRIPTS GO HERE ### use: ${PATCH_USER}
## Make the user do the job himself 
## sudo -u ${PATCH_USER} echo "I am myself v${UPDATE_PATCH_KVERNO}."
#
#
################STOP#USER#PATCH#
## Set and refresh the current version into inklist for the patch user
#sed -i "s/USER_KVERNO=.*/USER_KVERNO=${UPDATE_PATCH_KVERNO}/g" /home/${PATCH_USER}/.vrk/configs/stationinfo
#  fi
# fi
#fi
#done
## Global patch
#if [ $(echo "${UPDATE_PATCH_KVERNO}>${KVERNO}"|bc) = 1 ]; then
###### GLOBAL SCRIPTS GO HERE #####
#
#
## Set and refresh the current version into inklists
#sed -i "s/KVERNO=.*/KVERNO=${UPDATE_PATCH_KVERNO}/g" /var/local/vrk/vrkverno
#. /var/local/vrk/vrkverno
#fi
################END#UPDATE#PATCH#




MIN_KVERNO=0.200


# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo ./govrk
"
exit 0
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./govrk
"
exit 0
fi

# Check if present
if [ ! -d "/home/${SUDO_USER}/vrk" ]; then
echo "The vrk folder is not in the right place. I quit."
exit 22
fi

# Include the configs
. /var/local/vrk/vrkverno

# Check minimal updateable version
if [ $(echo "${MIN_KVERNO}>${KVERNO}"|bc) = 1 ]; then
echo "Can't run. The minimum version to run is ${MIN_KVERNO}. This Vrk version is ${KVERNO}. I quit."
exit 0
fi

# Vrk user update
## Check if Vrk Staion is installed for this user
cd /home
for PATCH_USER in ./*/
do
if [ -d "/home/${PATCH_USER}" ]; then
 if [ -f "/home/${PATCH_USER}/.vrk/configs/stationinfo" ]; then
. /home/${PATCH_USER}/.vrk/configs/stationinfo
  if [ "${VRK_INSTALLED}" = "YES" ]; then
## Update/refresh Bosses, Surfers, Droids, and Donjon
rm -rf /var/local/vrk/boss/*
rm -rf /var/local/vrk/surf/*
rm -rf /var/local/vrk/donjon/*
cp -rf /home/${SUDO_USER}/vrk /var/local/
chmod +x /var/local/vrk/boss/*
chmod +x /var/local/vrk/surf/*
chmod +x /var/local/vrk/donjon/*
chmod +x /var/local/vrk/donjon/vrktemplates/7_BASH
chmod +x /var/local/vrk/droids/*
## Refresh the links for the user
/var/local/vrk/boss/vrkfresh ${PATCH_USER}
  fi
 fi
fi
done


# Run version-by-version updates


UPDATE_PATCH_KVERNO=0.301

# Run the update scripts for this patch
cd /home
for PATCH_USER in ./*/
do
if [ -d "/home/${PATCH_USER}" ]; then
 if [ -f "/home/${PATCH_USER}/.vrk/configs/stationinfo" ]; then
. /home/${PATCH_USER}/.vrk/configs/stationinfo
  if [ $(echo "${UPDATE_PATCH_KVERNO}>${USER_KVERNO}"|bc) = 1 ]; then
##### PER-USER SCRIPTS GO HERE ###
# Add bossability declaration and properly update boards
if grep -q "USER_BOSSYN" "/home/${PATCH_USER}/.vrk/configs/stationinfo"; then
echo "Already a known boss..."
else
echo "USER_BOSSYN=\"CAN_BOSS\"" >> /home/${PATCH_USER}/.vrk/configs/stationinfo
. /home/${PATCH_USER}/.vrk/configs/stationinfo
/var/local/vrk/boss/vrkfresh ${PATCH_USER}
fi

# vGit
if grep -q "VGIT_INS" "/home/${PATCH_USER}/.vrk/configs/stationinfo"; then
echo "Already has vGit..."
else
echo "VGIT_INST=\"NOT_YET\"" >> /home/${PATCH_USER}/.vrk/configs/stationinfo
fi

###############STOP#USER#PATCH#
# Set and refresh the current version into inklists
sed -i "s/USER_KVERNO=.*/USER_KVERNO=${UPDATE_PATCH_KVERNO}/g" /home/${PATCH_USER}/.vrk/configs/stationinfo
  fi
 fi
fi
done
# Global patch
if [ $(echo "${UPDATE_PATCH_KVERNO}>${KVERNO}"|bc) = 1 ]; then
##### GLOBAL SCRIPTS GO HERE #####
# Fix the locale problem in older versions
/var/local/vrk/boss/vrklocale

# Set and refresh the current version into inklists
sed -i "s/KVERNO=.*/KVERNO=${UPDATE_PATCH_KVERNO}/g" /var/local/vrk/vrkverno
. /var/local/vrk/vrkverno
fi
###############END#UPDATE#PATCH#


UPDATE_PATCH_KVERNO=0.302

# Run the update scripts for this patch
cd /home
for PATCH_USER in ./*/
do
if [ -d "/home/${PATCH_USER}" ]; then
 if [ -f "/home/${PATCH_USER}/.vrk/configs/stationinfo" ]; then
. /home/${PATCH_USER}/.vrk/configs/stationinfo
  if [ $(echo "${UPDATE_PATCH_KVERNO}>${USER_KVERNO}"|bc) = 1 ]; then
##### PER-USER SCRIPTS GO HERE ###
cp -f /var/local/vrk/donjon/inkVerb-avatar.png /usr/share/pixmaps/faces/
sed -i "s/Icon=.*//g" /var/lib/AccountsService/users/${PATCH_USER}
echo "Icon=/usr/share/pixmaps/faces/inkVerb-avatar.png" >> /var/lib/AccountsService/users/${PATCH_USER}

###############STOP#USER#PATCH#
# Set and refresh the current version into inklists
sed -i "s/USER_KVERNO=.*/USER_KVERNO=${UPDATE_PATCH_KVERNO}/g" /home/${PATCH_USER}/.vrk/configs/stationinfo
  fi
 fi
fi
done
# Global patch
if [ $(echo "${UPDATE_PATCH_KVERNO}>${KVERNO}"|bc) = 1 ]; then
##### GLOBAL SCRIPTS GO HERE #####
# Update Vallpaper
if [ -L "/usr/share/images/vall" ]; then
rm -f /usr/share/images/vall
fi
/var/local/vrk/boss/install-vubuntu-vallpaper

# Set and refresh the current version into inklists
sed -i "s/KVERNO=.*/KVERNO=${UPDATE_PATCH_KVERNO}/g" /var/local/vrk/vrkverno
. /var/local/vrk/vrkverno
fi
###############END#UPDATE#PATCH#

UPDATE_PATCH_KVERNO=0.303

# Run the update scripts for this patch
cd /home
for PATCH_USER in ./*/
do
if [ -d "/home/${PATCH_USER}" ]; then
 if [ -f "/home/${PATCH_USER}/.vrk/configs/stationinfo" ]; then
. /home/${PATCH_USER}/.vrk/configs/stationinfo
  if [ $(echo "${UPDATE_PATCH_KVERNO}>${USER_KVERNO}"|bc) = 1 ]; then
##### PER-USER PATCH SCRIPTS GO HERE ### use: ${PATCH_USER}
# Make the user do the job himself 
# sudo -u ${PATCH_USER} echo "I am myself v${UPDATE_PATCH_KVERNO}."
chown -R ${PATCH_USER} /home/${PATCH_USER}/.vrk/myWall

###############STOP#USER#PATCH#
# Set and refresh the current version into inklist for the patch user
sed -i "s/USER_KVERNO=.*/USER_KVERNO=${UPDATE_PATCH_KVERNO}/g" /home/${PATCH_USER}/.vrk/configs/stationinfo
  fi
 fi
fi
done
# Global patch
if [ $(echo "${UPDATE_PATCH_KVERNO}>${KVERNO}"|bc) = 1 ]; then
##### GLOBAL SCRIPTS GO HERE #####
# Kid3
apt install -y kid3

# Set and refresh the current version into inklists
sed -i "s/KVERNO=.*/KVERNO=${UPDATE_PATCH_KVERNO}/g" /var/local/vrk/vrkverno
. /var/local/vrk/vrkverno
fi
###############END#UPDATE#PATCH#


UPDATE_PATCH_KVERNO=0.304

# Run the update scripts for this patch
cd /home
for PATCH_USER in ./*/
do
if [ -d "/home/${PATCH_USER}" ]; then
 if [ -f "/home/${PATCH_USER}/.vrk/configs/stationinfo" ]; then
. /home/${PATCH_USER}/.vrk/configs/stationinfo
  if [ $(echo "${UPDATE_PATCH_KVERNO}>${USER_KVERNO}"|bc) = 1 ]; then
##### PER-USER PATCH SCRIPTS GO HERE ### use: ${PATCH_USER}
# Make the user do the job himself 
# sudo -u ${PATCH_USER} echo "I am myself v${UPDATE_PATCH_KVERNO}."


###############STOP#USER#PATCH#
# Set and refresh the current version into inklist for the patch user
sed -i "s/USER_KVERNO=.*/USER_KVERNO=${UPDATE_PATCH_KVERNO}/g" /home/${PATCH_USER}/.vrk/configs/stationinfo
  fi
 fi
fi
done
# Global patch
if [ $(echo "${UPDATE_PATCH_KVERNO}>${KVERNO}"|bc) = 1 ]; then
##### GLOBAL SCRIPTS GO HERE #####
# Vallpaper
mv /var/local/vall/rooms/vubuntu/vubuntu /var/local/vall/rooms/vubuntu/vubuntu
rm -rf /usr/share/backgrounds/vubuntu
rm -rf /usr/share/images/vall
mkdir /usr/share/images/vall
ln -sfn /var/local/vall/rooms/vubuntu/vubuntu /usr/share/backgrounds/
ln -sfn /var/local/vall/rooms/vubuntu/vubuntu /usr/share/images/vall/
ln -sfn /var/local/vall/rooms/vubuntu/vubuntu/vubuntu-wallpapers.xml /usr/share/gnome-background-properties/
## MATE
if [ -d /usr/share/mate-background-properties ]; then
ln -sfn /var/local/vall/rooms/vubuntu/vubuntu/vubuntu-wallpapers.xml /usr/share/mate-background-properties/
fi
## Cinnamon
if [ -d /usr/share/cinnamon-background-properties ]; then
ln -sfn /var/local/vall/rooms/vubuntu/vubuntu/linuxmint-${VALL_ROOM}.xml /usr/share/cinnamon-background-properties/
fi


# Set and refresh the current version into inklists
sed -i "s/KVERNO=.*/KVERNO=${UPDATE_PATCH_KVERNO}/g" /var/local/vrk/vrkverno
. /var/local/vrk/vrkverno
fi
###############END#UPDATE#PATCH#



# Cleanup
rm -rf /home/${SUDO_USER}/vrk

# Finish
echo "Vrk Station and users are Vrking at v${KVERNO}"

