#!/bin/sh
# inkVerb Station-wide config file, verb.ink
## This is used for language folder variables in surfer scripts

INT_DESKTOP_DIR="Desktop"
INT_DOWNLOAD_DIR="Downloads"
INT_TEMPLATES_DIR="Templates"
INT_PUBLICSHARE_DIR="Public"
INT_DOCUMENTS_DIR="Documents"
INT_MUSIC_DIR="Music"
INT_PICTURES_DIR="Pictures"
INT_VIDEOS_DIR="Videos"
