#!/bin/sh
# inkVerb Station-wide config file, verb.ink
## This is used for language folder variables in surfer scripts

XDG_DESKTOP_DIR="Desktop"
XDG_DOWNLOAD_DIR="Downloads"
XDG_TEMPLATES_DIR="Templates"
XDG_PUBLICSHARE_DIR="Public"
XDG_DOCUMENTS_DIR="Documents"
XDG_MUSIC_DIR="Music"
XDG_PICTURES_DIR="Pictures"
XDG_VIDEOS_DIR="Videos"
