#!/bin/sh
# Color scheme for Xfce terminal

# Create the directory
mkdir -p ~/.config/xfce4/terminal

# Echo the settings
echo "[Configuration]
ColorPalette=#0c0d0e;#e31a1c;#31a354;#dca060;#3182bd;#756bb1;#80b1d3;#b7b8b9;#737475;#e31a1c;#31a354;#dca060;#3182bd;#756bb1;#80b1d3;#fcfdfe
FontName=DejaVu Sans Mono 11
MiscAlwaysShowTabs=FALSE
MiscBell=FALSE
MiscBordersDefault=TRUE
MiscCursorBlinks=FALSE
MiscCursorShape=TERMINAL_CURSOR_SHAPE_BLOCK
MiscDefaultGeometry=80x24
MiscInheritGeometry=FALSE
MiscMenubarDefault=TRUE
MiscMouseAutohide=FALSE
MiscToolbarDefault=FALSE
MiscConfirmClose=TRUE
MiscCycleTabs=TRUE
MiscTabCloseButtons=TRUE
MiscTabCloseMiddleClick=TRUE
MiscTabPosition=GTK_POS_TOP
MiscHighlightUrls=TRUE
MiscScrollAlternateScreen=TRUE
ColorBold=#3131a3a35454
ColorForeground=#b7b7b8b8b9b9
ColorCursor=#3131a3a35454
ColorBoldUseDefault=FALSE
ColorBackground=#0c0c0d0d0e0e
" > ~/.config/xfce4/terminal/terminalrc

